var ENG={

mentex:[

"O Edison<br><span class='bt1'>Receptor de Vozes de Espíritos e Fantasmas<br></span>Guia de Uso<br>Sobre a Comunicação Sobrenatural (um aviso)<br><br>Quando estiver contatando um Fantasma ou Espírito, o estado emocional deles afeta diretamente o potencial elétrico ou estado de 'Energia'. Os fantasmas podem se manifestar em altos ou baixos estados de energia, mas para comunicação com vozes é requerido um estado de energia baixa<br><br>Fantasmas podem ser provocados para transitar entre estados de energia quando questionados de forma agressiva ou provocativa. Se um fantasma entrar num estado de energia alto, o Receptor irá receber apenas um ruído alto e a comunicação não poderá ser continuada.<br>Fantasmas em um estado de energia alto frequentemente se manifestam fisicamente, sem ajuda óptica ou eletrônica. Isso ocorre em diferentes locais. Por favor, tenha em mente que entidades sobrenaturais são as almas de pessoas já falecidas. Trate-os com o devido respeito.",

"energia aumentada<br>pela conversa<br><br>ESTADO BAIXO<br><br><br><br>VOZ PODE SER<br>OUVIDA",

"<br><br><br>ESTADO ALTO<br><br><br><br><br>PODE SE MANIFESTAR<br>FISICAMENTE<br><br>energia dissipada<br>pela manifestação",

"<div class='ht'><span style='font-size:170%'>Conselho para Gameplay</span><br><br>Jogue At Dead Of Night na calada da noite ou pelo menos em um quarto escuro e garanta que tenha o mínimo de sons de fundo ou use um headset se você estiver jogando sozinho(a).<br><br>Você precisará ser capaz de enxergar nas áreas mais escuras da tela, já que grande parte do hotel está escuro e algumas vezes apenas a sombra do Jimmy poderá ser vista. Use o Ajuste de Brilho (Tecla U e I) para iluminar as sombras se for preciso.<br><br>A voz do Jimmy pode ser ouvida se ele estiver no mesmo andar que você. Se você escutar com atenção, poderá ouvir os passos dele também, o que pode te ajudar a saber o quão próximo ele está. Fantasmas também fazem sons, se você quiser ouvir com mais atenção, clique D para atenuar o som ambiente por um momento.<br><br>Se você precisar de assistência auditiva selecione a opção 'Audiodescrição' abaixo de Legendas. Se você não precisa é aconselhável deixar essa opção desativada.<br><br>O ponteiro da bússola aponta para fantasmas mesmo atrás de paredes. Então se você não encontrar um fantasma na direção que está apontando, tente andar pelos corredores. A bússola gira devagar quando não há fantasmas em volta e gira mais rapidamente quando você se aproxima de algum.<br><br>Lembre-se que você pode olhar atráves da fechadura para ver dentro dos quartos e pode correr mais rápido pelos corredores movendo a seta para o topo da tela.</div>",

"<div class='ht'><span style='font-size:170%'>Jimmy e T.D.I.</span><br><br>A história de Jimmy é uma representação teatral e simbólica de alguém lutando com dois caminhos morais opostos e não pretende ser uma representação literal do transtorno psicológico real conhecido como T.D.I. ou Transtorno Dissociativo de Identidade.<br><br>O T.D.I. é uma doença angustiante e debilitante, muitas vezes (mas não sempre) associada a abusos na infância. T.D.I. não se correlaciona de forma alguma com comportamentos imorais ou criminosos. Os portadores de T.D.I. merecem compaixão, mas frequentemente enfrentam condenação ou desconfiança, geralmente como resultado do mal-entendimento público.<br><br>Não foi nossa intenção insinuar que Jimmy possui esse transtorno, e aceitamos plenamente que perpetuar estereótipos é prejudicial aos portadores e impede o progresso e a compreensão. Pedimos sinceras desculpas por qualquer sofrimento ou dor causados àqueles que sofrem de T.D.I.<br><br>Para mais informações, por favor veja:<br><br>https://survivorsnetwork.org.uk/resource/dissociative-identity-disorder-d-i-d/</div>",

"Um Agradecimento ao<br>Talento Fabuloso dos Atores de<br><br><table><tr><td><span class='h5'>Jimmy</span><br><span class='ht'>Huld Martha</span><br><br><span class='h5'>Rose</span><br><span class='ht'>Joanna Bond</span><br><br><span class='h5'>Dr Bose</span><br><span class='ht'>Rohit Gokani</span><br><br></td><td><span class='h5'>Maya</span><br><span class='ht'>Chloe Booyens</span><br><br><span class='h5'>Harvey</span><br><span class='ht'>Karl Haynes</span><br><br><span class='h5'>Amy<span><br><span class='ht'>Daisy Follin</span><br><br></td></tr></table><span class='h5'>E os Atores Coadjuvantes</span><table><tr><td><span class='ht'>Rachel Alfieri<br>Paige Ryan<br>Sam Follin</span></td><td><span class='ht'>Jamie Follin<br>Clare Follin<br>Tom Follin</span></td></tr></table><br><span class='h5'>E Um Agradecimento Especial a</span><br><table><tr><td><span class='ht'>Mark Wilson</span></td><td><span class='ht'>Fay Wilkins</span></td><td><span class='ht'>Daniel Alfieri<span></td><td><span class='ht'>Sally Alfieri</span></td><td><span class='ht'>Luke Chase</span></td></tr></table><br><span class='h7'>Criado por Tim 'so what do you do now' Follin<br>©2020 Baggy Cat Ltd</span></span>",

"&#160;&#160;&#160;&#160;&#160;Audiodescrição<br><br><span class='h2'>Adiciona legendas detalhadas e uma descrição de texto dos sons ouvidos durante o jogo, juntamente com o indicador de volume.<br><br>Se você não precisar de assistência é recomendado deixar esta opção desligada.</span>",

"&#160;&#160;&#160;&#160;&#160;Legendas<br><br><span class='h2'>Adiciona legendas básicas ao jogo e ao prólogo.</span>",

"Ainda não há visões<br>para rever.",

"COMEÇAR NOVO JOGO",

"<span class='h9'>A História de Jimmy Hall</span><br><br><span class='h2'>Descubra os segredos de Jimmy ao perguntar para os espiritos sobre as coisas que você encontrar e depois crie conexões para fazê-los aparecer. Jimmy fará o seu pior para impedir que você descubra a verdade.</span>",

"<span class='h9'>Final do Último Jogo</span><br><br><span class='h2'>Jogue seu último jogo completado a partir do momento em que Jimmy convidou você para conhecer Hugo.</span>",

"<span class='h9'>O Resgate Final (novo jogo)</span><br><br><span class='h2'>Resgate todos os seus amigos enquanto evita ser atacado pelo Jimmy. Um golpe e você está morto! Este jogo não salva e você pode retornar ao seu jogo atual quando escapar ou se for atacado.</span>",

"Assistir Tutorial Completo",

"Assistir 'A Perseguição'",

"Assistir 'A Estratégia'",

"Assistir 'Os Mortos'",

"Assistir 'Talento Da Maya'",

"Assistir Prólogo",

"Assistir 'A Chegada De Maya'",

"Assistir 'Hugo Assume O Controle'",

"Assistir '2:30AM'",

"Assistir 'O Receptor De Espiritos'",

"Estatísticas",

"Começar um Novo Jogo",

"Analisar Visões",

"Instruções do Receptor",

"Assistir Tutorial e Intro",

"Legendas e Descrições",

"Créditos",

"Conselho de Gameplay",

"Jimmy E T.D.I.",

"Sair do hotel<br><span class='h2'>Salvar e Sair</span>",

"Tem a certeza que quer<br>sair do hotel agora?",

"SIM! ME DEIXE SAIR!",

"<br>NÃO TEM<br>ITENS<br>PARA VER AINDA",

"O Jimmy te atacou pela última vez.<br><br>A tua fuga acaba aqui.<br><br>Mas podes sempre tentar de novo...",

"Entrar No Hotel<br><span style='font-size:50%'>Voltar ao último jogo salvo</span>",

"Entrar No Hotel<br><span style='font-size:70%'>Começar um novo jogo</span>",

"COMEÇAR NO MODO PADRÃO",

"COMEÇAR NO MODO EXTREMO",

"Salvar o jogo atual",

],

achtex:[

  "Você completou",
  "da história",
  "Você evitou ser atacado",
  "Jimmy atacou você uma vez",
  "Jimmy atacou você duas vezes",
  "Jimmy atacou você",
  "vezes",
  "Você descobriu o segredo do hotel",
  "História",
  "Concluída",
  "",
  "",
  "",
  "Você salvou todos os seus amigos",
  "Você tem de achar a saída do hotel",
  "Você finalizou o jogo!",
  "Ainda não há estatisticas para mostrar",
  "Estatísticas",
  "Conquistas",
  "Você completou a história de Amy",
  "Você completou a história de Dr Bose",
  "Você completou a história de Harvey",
  "Você completou a história de Rose",
  "Você completou a história principal",
  "Você completou a história principal sem levar dano",
  "Você completou At Dead Of Night",
  "Você resgatou todos em um jogo rápido",
  "Você completou At Dead Of Night sem levar dano!",
  "Voltar para Sea View",
  "Ainda não tens conquistas",
  "O jogo salva após visões de fantasmas, após provocar reações de fantasmas (somente após desligar o Receptor) e se o Jimmy te nocautear.",
  "Você completou a história principal no MODO EXTREMO",
  "Você completou a história principal no MODO EXTREMO sem levar dano",
  "Você completou At Dead Of Night no MODO EXTREMO",
  "Você completou At Dead Of Night no MODO EXTREMO sem levar dano!",
  "Todos os seus amigos saíram em segurança.",

],

selx:[

  "Não Teve uma Resposta",
  "Você ainda não perguntou sobre isso",
  "Entre em contato com um espírito para perguntar sobre isso",
  "Clique no Item Para Ver A Resposta De Cada Espírito",
  "Encare a porta trancada para testar a chave",
  "Selecione para perguntar sobre isso",
  "não teve uma resposta",
  "Disse:",
  "TENHA UMA BOA VIAGEM<brvolte brevemente",
  "Jogo Atual Salvo",
  "Comece Um Jogo Primeiro",

],

numwo:[

  "Você Tem Apenas Um Amigo Para Resgatar",
  "Você Tem Dois Amigos Para Resgatar",
  "Você Tem Três Amigos Para Resgatar",
  "Você Tem Quatro Amigos Para Resgatar",
  "Você Tem Cinco Amigos Para Resgatar",

],

numwa:[

  "Você Resgatou Cinco Amigos",
  "Você Resgatou Quatro Amigos",
  "Você Resgatou Três Amigos",
  "Você Resgatou Dois Amigos",
  "Você Resgatou Um Amigo",

],

helx:"<span class='ht'>&#8679;S</span> Salvar o Jogo | <span class='ht'>Esc</span> Alternar Menu | <span class='ht'>D</span> Reduzir Sons de Ambiente | <span class='ht'>Q/W</span> Ajustar Volume<br><span class='ht'>&#8679;X</span> Sair Rápido | <span class='ht'>U/I</span> Ajuste de Brilho | <span class='ht'>O/P</span> Ajuste de Saturação | <span class='ht'>R</span> Redefinir Níveis",

resk:[

  "Você achou<br><br>Cinco Chaves-Raxa<br><br><span style='font-size:50%'>Você tem cinco amigos por resgatar</span>",
  "Espere Eles<br><br>Fugirem<br><br>",
  "<span style='font-size:50%'>Você resgatou todos os seus amigos</span>",
  "<span style='font-size:50%'>Você tem mais um amigo para resgatar</span>",
  "<span style='font-size:50%'>Você tem mais dois amigos para resgatar</span>",
  "<span style='font-size:50%'>Você tem mais três amigos para resgatar</span>",
  "<span style='font-size:50%'>Você tem mais quatro amigos para resgatar</span>",

],

ityptex:[

  "Mostrando Tudo",
  "Mostrando Itens Encontrados",
  "Mostrando Visões",
  "Mostrando Conexões",
  "Mostrando Chaves"

],

intros:[

  "Esse é o dispositivo que você encontrou. Clique aqui para o ligar.",
  "Ele detecta vozes de espíritos se você estiver perto o suficiente deles.",
  "Se você não viu o tutorial, vá até o MENU e veja o vídeo ensinando antes de continuar!",
  "O aparelho que você achou detecta vozes de espíritos se você estiver perto o suficiente deles.",

  "Se você não viu o tutorial, vá até o MENU e veja o vídeo ensinando antes de continuar!",
  "Esta é uma lista de coisas que você viu e chaves coletadas.",

  "Maya pode perguntar aos espíritos sobre as coisas dessa lista.",
  "Esta é uma lista de coisas que você viu e chaves coletadas.",

  "Maya pode perguntar aos espíritos sobre as coisas dessa lista.",
  "Você só pode usar o espelho da previsão quando o ícone estiver visível,",

  "seja perto da porta nos quartos ou na cozinha do térreo.",
  "Use o espelho para ver pistas sobre onde ir ou quais itens usar em seguida,",
  "Ele também vai ajudar você a localizar chaves perdidas, bússolas e a caixa de fantasmas.",
  "Você só pode usar o espelho de previsão quando o ícone estiver visível,",

  "seja perto da porta nos quartos ou na cozinha do térreo.",
  "Use o espelho para ver pistas sobre onde ir ou quais itens usar em seguida,",
  "Ele também vai ajudar você a localizar chaves perdidas, bússolas e a caixa de fantasmas.",
  "A bússola aponta para espíritos próximos.",

  "Pergunte aos espíritos sobre coisas que você viu.",

  "Você verá a resposta deles ao selecionar o item.",
  "Combine duas respostas que você acha que se conectam para descobrir a história do espírito.",

  "Combine respostas de visões com respostas de itens para um progresso mais rápido.",
  "Se o espírito parar de responder, eles podem ter se afastado.",

  "Use uma bússola, procure por luzes piscando e preste atenção a sons.",
  "Inicie conversas com os espíritos fazendo perguntas introdutórias.",

  "Se não houver resposta, não há espíritos por perto.",
  "Um ruído alto significa que há um espírito em um estado de alta energia por perto.",
  "Inicie conversas com os espíritos fazendo perguntas introdutórias.",

  "Se não houver resposta, não há espíritos por perto.",
  "Um ruído alto significa que há um espírito em um estado de alta energia por perto.",
  "Jimmy Hall está neste andar procurando por você. Fique longe dele!",

  "Para experimentar chaves, abra o inventário, vá até à porta e selecione uma chave.",

  "As portas podem ser trancadas ou destrancadas com a chave certa.",
  "Para experimentar chaves, abra o inventário, vá até à porta e selecione uma chave.",

  "As portas podem ser trancadas ou destrancadas com a chave certa.",
  "O jogo será salvo aqui pela última vez.",

  "Agora você precisa resgatar seus amigos...<br>mas se o Jimmy pegar você, o jogo acaba!",
  "Essa é a última<br>pessoa resgatada.<br>Agora encontre a saída<br>e fuja!",

  "Ande em frente para os retirar do quarto",

],

substan:[

  "Eu não sei.",
  "Talvez.",
  "Não",
  "VOZ<br>VAGAMENTE<br>OUVIDA/",
  "RUÍDO NO<br>RECEPTOR/"

],

subrepa:[
[
  "Oi?",
  "Oi",
  "Oi.",
  "Oi",
  "Oi.",
  "Oi"
],[
  "Oi?",
  "Oi?",
  "Oi?",
  "Oi?"
],[
  "Oi?",
  "Eu consigo te ouvir.",
  "Eu consigo te ouvir.",
  "Eu consigo te ouvir."
],[
  "Oi?",
  "Eu consigo te ouvir.",
  "Oi?",
  "Eu consigo te ouvir.",
  "Eu consigo te ouvir."
],
],

subrepb:[
[
  "Eu sou a Amy Bell. Tenho dez anos.",
  "Sim, sou a Amy.",
  "Sim, sou a Amy.",
  "Sim, sou eu.",
  "Sim sou a Amy.",
  "Sim. sou a Amy.",
  "Sim, é a Amy.",
  "Sim, sou eu."
],[
  "Doutor Bose. Sou um psiquiatra clínico.",
  "Sim, sou o Doutor Bose.",
  "Sou o Doutor Bose.",
  "Sim. sou o Doutor Bose.",
  "Sim.",
  "Sim sou eu.",
  "Sim, sou o Doutor Bose."
],[
  "Harvey. Eu administro o lugar.",
  "Sim.",
  "Sim, é o Harvey.",
  "Sim. É o Harvey.",
  "Sim. É o Harvey.",
  "Sim, é o Harvey."
],[
  "Rose, Rose Hall. Este é o meu hotel.",
  "Sim.",
  "Sim. Sou a Rose.",
  "Sim.",
  "Sim, Sou a Rose.",
  "Sim.",
  "Sim. Sou a Rose."
],
],

subcall:[

  "JIMMY?",
  "OI!",
  "ESTOU AQUI!",
  "AQUI!",
  "POR AQUI!",

],

subin:[

  "Tem alguém aí?",
  "Tem alguém aí?",
  "Tem alguém aí?",
  "Alguém está aí?",
  "Alguém está aí?",
  "Alguém está aí?",
  "Quem está aí?",
  "Oi?",
  "Oi?",
  "Alguém está aí?",
  "Alguém está aí?",

],

subnm:[

  "É a Amy?",
  "É o Dr&#160;Bose?",
  "É o Harvey?",
  "É a Rose?",
  "Qual é o seu nome?",

],

subrepc:[

  ["H","Rose, mas ela nunca usou.","R","Eram minhas. Eu queria ir embora, mas nunca tive a chance."],
  ["R","Jimmy comprou eles, pra parecer que ele tinha ganho prêmios."],
  ["A","Era minha. Foi pro meu aniversário, mas foi roubada.","H","Era a bolsa daquela menina, pobrezinha.","R","Pertencia à garotinha."],
  ["A","Eu não sabia o que eram, até o Jimmy me mostrar.","P","Melhor você perguntar pro Jimmy.","H","Eram minhas coisas, mas eu não deixava elas juntas.","R","Eu não sei. Eram do Harvey."],
  ["A","Era do Jimmy. Eu não gostava.","P","Eu vi o Jimmy brincando com isso. Eu achei perigoso.","H","A gente tinha um mostruário de armas medievais. Jimmy roubou.","R","Ficava junto de uma armadura que tínhamos. Mas desapareceu."],
  ["A","Eu não sei, mas crianças não deveriam beber álcool.","P","Elas provavelmente são do bar.","H","Eu não lembro, mas não tem nada errado em tomar um drink.","R","Harvey deve ter colocado lá."],
  ["A","O menino costumava desenhar eles.","P","Jimmy. Ele costumava desenhá-los.","H","Adivinha? Jimmy! Ele tinha uma imaginação muito violenta, o pequeno Jimmy.","R","Jimmy costumava desenhar imagens sobre a guerra. Ele era como os outros meninos."],
  ["P","Jimmy achou e vestiu.","H","O chef! Quem mais usaria o toque do Chef?","R","Nosso Chef costumava usar."],
  ["A","Talvez pudesse ser meu.","P","Era meu. Eu mantive, em caso de precisar de evidência..","H","Eu não sei, mas talvez tenha a ver com o doutor."],
  ["P","Pode ajudar a tratar comportamento impulsivo, em algumas pessoas.","H","Provavelmente o doutor deixou.","R","Pertencia ao Doutor Bose."],
  ["P","Eu não sei, mas Jimmy encontrou.","H","Estava atrás da bancada na recepção. Eu não sei da onde veio.","R","Pertencia ao meu marido."],
  ["A","Jimmy fez. Não sei porque. Ele era estranho.","P","Jimmy fez. Era um aviso, eu devia ter previsto.","H","Jimmy - ele costumava guardar recortes de notícias sobre professores e médicos abusivos. Ele não era um garoto normal.","R","Harvey disse que Jimmy fez isso. Eu não lembro."],
  ["P","Eu amarrei eles juntos. Foi um experimento."],
  ["H","Estava dando choques elétricos. Eu mantive para que a polícia pudesse checar..","R","Harvey jogou fora. Ele disse que era perigoso."],
  ["A","Eu não sei. O garoto costumava brincar com isso.","P","Harvey os manteve. Eu não sei porque.","H","Eu guardei, no caso de precisar.","R","Eles eram do meu marido, quando ele era professor."],
  ["A","Estava num armário, no hotel. Eu vi.","P","O hotel tinha um mostruário de armas antigas.","H","Era do mostruário de armas que tínhamos. Jimmy era apegado.","R","Era do mostruário que Harvey costumava ter. Mas eu não gostava daquilo no hotel."],
  ["H","Elas eram da antiga porta da caldeira.","R","Elas eram para a sala da caldeira. Mas tivemos que substituir a porta."],
  ["P","Eu não ouvi sobre isso.","H","Sim - eles conseguiram manter isso, mas eu perdi muitas coisas.","R","Sim. Mas controlamos a tempo, antes que se espalhasse."],
  ["P","Era do Harvey. Eu não gostava disso estar no hotel.","H","Era meu. Pertencia ao meu pai. Ainda tem algumas balas nela.","R","Harvey. Mas eu mantinha no meu quarto."],
  ["A","Jimmy mostrou para mim. Mas não era dele.","H","Não é uma adaga, é um abridor de cartas. Não é para ser afiado.","R","É um abridor de cartas. Foi um presente de alguém."],
  ["R","Era o ato de comédia do Jimmy."],
  ["P","Eu não vi eles.","H","Eu não lembro disso.","R","Jimmy quebrou eles."],
  ["A","Jimmy costumava carregar com ele por ai","P","Era do Jimmy. Ele sempre mantinha em seu bolso. Ele não me disse para quê usou.","H","Jimmy carregava com ele. Sei lá porquê.","R","Jimmy carregava fios com ele por ai. Ele gostava de brincar por ai com eletrônicos."],
  ["R","Jimmy escreveu."],

  ["H","Provavelmente pertencia à Rose.","R","Era minha. Alguém me fez uma oferta irrecusável."],
  ["A","Eu não sei. Eu não vi um bebê.","R","Era pro bebê. Eu guardava na gaveta do criado-mudo."],
  ["R","Jimmy é filho do Hugo. De qualquer maneira."],
  ["A","Era eu - um menino chamado Jimmy me trancou no porão. Aí ele começou a roubar minhas coisas.","P","Era filha de um hóspede do hotel. Jimmy não era legal com ela.","H","Ela estava hospedada com a família no hotel.","R","Ela era uma hóspede do hotel."],
  ["A","Porque ele achou engraçado. Ele devolveu, mas ai estragou de qualquer jeito.","P","Não faço ideia, é só o tipo de coisa que ele fazia.","H","Quem sabe. Ele talvez achou que seria engraçado.","R","Ele não pegou. A menina estava mentindo. Jimmy não roubava coisas."],
  ["A","Minha mão queimou, tava doendo de verdade, mas eu não podia contar para ninguém.","P","A mão dela queimou bastante, bem feio, mas Jimmy pensou que era tudo uma piada.","H","Ela se queimou, pra caralho.","R","Ela se queimou, mas continuou fazendo coisas perigosas assim. Ela era esquisita."],
  ["A","Eu estava tentando achar o doutor, mas Jimmy me ameaçou e me fez ficar.","H","Talvez ela tava com medo do Jimmy.","R","Eu não sei, pode não ter sido nada. Ela era uma menina estranha."],
  ["A","O menino disse que era remédio. Tinha um gosto horrível.","P","Eu não estava lá, mas acho que ela bebeu álcool."],
  ["A","Eu me senti muito leve, eu achei mesmo que poderia pular até o fundo.","P","Jimmy fez a menina beber muito.","H","Ela bebeu uma garrafa de whiskey, ela não sabia o que tava fazendo.","R","Eu não sei. Eu não conhecia ela direito."],
  ["A","Eu pulei, mas aí tudo ficou escuro e eu não consegui acordar. Eu não consigo acordar mais. Eu não sei aonde eu tô.","P","Ela caiu pelas escadas lá do andar mais alto. Ela tava bêbada demais para saber o que estava fazendo. Foi a razão pela qual Rose entrou em contato comigo.","H","Ela despencou do andar mais alto, até lá embaixo. Eu sabia que o Jimmy tava por trás disso, só podia ser.","R","Ela caiu. Harvey culpou o Jimmy por isso. Foi culpa da garota, não do Jimmy."],
  ["P","Era eu - eu recebi uma ligação da Rose, a mãe do Jimmy. Ela queria falar comigo sobre ele, descobrir o que estava chateando ele. Mas o Harvey estava preocupado sobre a mente de Jimmy, as coisas que ele imaginava.","H","Era o Doutor Bose. Era pra ele ter ajudado o Jimmy, mas Jimmy tava além de qualquer ajuda.","R","Doutor Bose. Ele veio para ajudar o Jimmy."],
  ["P","Jimmy estava matando coisas, passarinhos, animais. Eu imaginei que ele precisava trabalhar sua empatia. Então eu pedi para ele pensar em algo legal que ele poderia fazer para mim. Fiquei surpreso, ele teva uma ideia na hora.","H","Jimmy falou que ele tinha achado por ai. O que ele estava fazendo com aquilo, é uma outra história.","R","Harvey disse que Jimmy tinha matado por si só, mas eu não acreditei."],
  ["P","Jimmy estava me fazendo um sanduíche. Ele trouxe pro meu quarto, como eu pedi. Eu não suspeitei que tinha algo errado, num primeiro momento.","H","O médico tava tentando educar o Jimmy, fazer ele ajudar. Errou feio.","R","Doutor Bose continuou tentando fazer o Jimmy fazer coisas que ele não queria."],
  ["P","Jimmy colocou cacos de vidro no meu sanduíche. Eu quase engasguei. Eu guardei o pano e os cacos para poder ir na polícia, mas eu percebi que subestimei a doença do Jimmy. Eu só precisava dar início ao tratamento, com urgência.","H","Ele conheceu o Jimmy da pior forma. As pegadinhas do Jimmy sempre iam longe demais.","R","Ele se cortou. Mas então ele tentou culpar o Jimmy. Ele fez aquilo com ele mesmo, não foi o Jimmy."],
  ["P","Jimmy se recusou a me deixar administrar a medicação. Eu tive que perseguir ele pelo hotel. Aí ele disse à Rose que eu tava forçando ele a tomar, que eu usei violência. Foi ridículo!","H","Sei lá, eu não tava lá.","R","Ele tava tentando medicar o Jimmy, sem minha permissão."],
  ["P","Eu estava preocupado que Rose acreditaria no Jimmy. Era uma mentira na cara lavada. Mas eu convenci a Rose que Jimmy estava inventando tudo.","H","Ele tava preocupado com o que o Jimmy poderia aprontar com ele. E ele tinha razão.","R","Porque ele tava preocupado com a reputação dele. Eu não sei em quem acreditar. mas eu decidi dar à ele uma segunda chance."],
  ["P","Eu pensei que, quando ele percebesse que foi pego mentindo, ele começaria a engajar mais comigo e fazer o que eu pedi. Ao invés disso ele só inventou outra mentira. Só que uma pior. Muito pior.","R","Ele estava conversando com o Jimmy, tentando controlar ele. Obrigá-lo a fazer coisas, coisas ruins. Eu nunca deveria ter confiado nele."],
  ["P","Rose me denunciou. Eu sabia que eles iriam me expulsar. Eu estaria sem carreira, sem futuro. Então eu decidi tomar o controle, de uma vez por todas.","H","Iam prender ele. Jimmy fodeu com ele. Mas eu não acreditei em nada.","R","Ele vieram prendê-lo. Ele mereceu tudo que teve."],
  ["P","Eu estava farto. Não tinha mais volta. Minha vida tinha acabado mesmo.","H","Porque ele foi forçado. Todo mundo pensou que ele tinha.... tocado o Jimmy. Jimmy foi esperto, tipo, muito esperto. O médico não tinha chance. Pobre alma.","R","Porque ele sabia que era culpado. Ele fez a coisa certa."],
  ["P","Foi o Harvey. Ele sabia que Jimmy estava mentindo sobre mim. Harvey entendeu.","H","Fui eu. Jimmy tava acusando o doutor. Rose acreditou nele, mas eu já tinha escutado aquela história outras vezes.","R","Foi o Harvey. Ele não acreditava no que Jimmy estava falando. Mas eu sei que ele não estava mentindo."],
  ["P","Jimmy nunca admitiu suas mentiras.","H","Óbvio que não! Ele só ria. Aí ele começou a montar pequenas armadilhas pra mim. Algumas não tão pequenas.","R","Não - como Jimmy poderia admitir algo que não era verdade? Harvey estava errado em implicar com Jimmy daquele jeito."],
  ["H","Ele sabia que era meu aquecedor, e ligou a tampa direto na rede elétrica. Quase me matou. Ele fez porque quis, mas a Rose não ia acreditar. Eu só sei que ele precisava tomar uma lição. Ele destruiu minha propriedade então eu decidi destruir a dele.","R","Harvey culpou o Jimmy, mas o aquecedor tava com defeito. Harvey deveria ter jogado fora."],
  ["P","Eu não sei, mas violência só torna as coisas piores.","H","Eu destruí a televisão dele, o video-game e essas coisas. Eu estava enfurecido; mas não adiantou. Só deixou ele pior. Ele logo se vingou.","R","Ele acabou com as coisas do Jimmy. Ele não conseguia controlar sua raiva."],
  ["H","Jimmy armou para atirar quando eu abrisse a porta. Eu tive que ir pro pronto-socorro, levar pontos e tomar injeções de tétano. Quando eu voltei, não consegui achar ele. Rose me disse que ele tava escondido no porão. Isso me deu uma ideia.","R","Harvey disse que Jimmy atirou uma flecha nele, mas eu sabia que Jimmy não usaria uma arma assim."],
  ["H","Eu queria dar ao Jimmy uma dose do seu próprio veneno. Eu pensei que ele não causaria nenhum dano lá embaixo. Tava errado.","R","Eu não sabia o que ele estava fazendo."],
  ["P","Eu não me lembro.","H","Nós conseguimos conter antes que fosse pior. Mas todas nossas fotos antigas, cartas e tudo que estava lá, se tornaram chamas. Jimmy tava fora de controle, eu tinha cansado dele. Eu queria que ele fosse embora.","R","Harvey culpou Jimmy, mas foi um fio desencapado que começou aquele incêndio. Foi um acidente."],
  ["P","Eu não sei. Mas Harvey não pôde controlar sua raiva.","H","Eu não sabia o que iria fazer. Ameaçar ele, expulsar ele do hotel.... O problema era, eu não imaginei que ele iria se preparar também.","R","Eu não sei. Harvey não deveria ter uma arma no hotel."],
  ["H","Eu tava procurando pelo Jimmy."],

  ["H","Jimmy se esgueirou atrás de mim, Eu não vi. Jimmy sempre ganha no final.","R","Harvey ficou louco. Jimmy só estava se defendendo."],
  ["H","Rose - A Rose acreditou no Jimmy. Ela defendeu ele, até o fim.","R","Fui eu. Eu tive que explicar para a polícia que a adaga era só um abridor de cartas e que Harvey tinha uma arma carregada. Jimmy agiu em legítima defesa. Eles compreenderam."],
  ["H","Jimmy - eles soltaram o Jimmy. Disseram que foi auto-defesa, que eu tinha tentando atirar nele. Mas eram tudo mentiras.","R","Jimmy - ele estava voltando pra casa. A polícia entendeu. Eles acreditaram, mas mudaram ele. Ele começou a me ajudar, ajudar a gerenciar o hotel. E ele encontrou um meio de trazer mais hóspedes."],
  ["H","Eu não sei quem ele era.","R","Eu estava gostando, estavámos fazendo dinheiro de novo. Tudo parecia estar melhorando até que.... Jimmy começou a agir estranho. Eu ouvi ele gritando, olhando pra si mesmo. Ele parecia zangado."],
  ["R","Jimmy - Eu não entendi de imediato, eu estava confusa. Mas então eu percebi. Jimmy não era quem estava fazendo aquelas coisas. Assim como espelhos, ele estava começando a estilhaçar. Jimmy não estava mais no controle."],
  ["H","Eu não sei, mas sei que Jimmy sempre estraga tudo eventualmente.","R","Não era o Jimmy no palco mais, era Hugo Punch, seu personagem cômico. Hugo começou a ofender seu público toda noite. Ele parecia gostar. Então uma noite após o show, uma hóspede disse ao Jimmy o que ela pensava sobre ele. Jimmy perdeu a paciência. Ele fez algo estúpido."],
  ["R","Jornalistas, eles queriam o Jimmy. Mas Jimmy não estava no controle, foi o Hugo Punch que amarrou a mulher. Jimmy não conseguia controlá-lo mais. Ele estava deprimido. Ele só queria deixar tudo para trás e ir embora."],
  ["R","Era o Jimmy. Ele tentou se matar. Por isso eu tive que contar à ele a verdade."],
  ["H","Eu não sei. Tiveram coisas que a Rose nunca me contou.","R","Hugo - eu enterrei ele sob concreto, em um quarto secreto. Eu deveria ter feito antes. Eu deixei ele abusar do Jimmy por tempo demais. Foi culpa minha Jimmy ter se tornado o que se tornou. Eu pensei que a culpa iria embora se eu contasse ao Jimmy. Eu estava errada, só piorou. Eu não conseguia aceitar o que eu fiz. Eu não poderia viver comigo mesma."],
  ["R","Se eu não tivesse feito comigo mesma, Jimmy teria feito, ou pior, Hugo teria. Hugo continua no comando, ainda hoje. Ele controla o Jimmy. Peça ao Jimmy que mostre aonde o Hugo mora."],
  ["H","Eu nunca conheci ele.","R","Ele era um mágico e artista. Ele comprou o hotel para promover seu show. Ele ficou famoso, estava na televisão. Eu trabalhei como assistente dele, então as coisas.... evoluíram."],
  ["R","Eu nunca soube o que ele queria. Havia apenas uma coisa que eu poderia dar à ele."],
  ["R","Hugo era um homem violento, vil e doente."],
  ["A","Sim, ele pegou quando eu não estava olhando e roubou meu dinheiro. Eu briguei com ele, mas ele não me deu ouvidos."],
  ["A","Ele encharcou meu brinquedo com aquela coisa na garrafa, eu odiava ele!"],
  ["A","Sim - ele tirou da parede, parece muito afiada. Ele me fez prometer não falar para ninguém e ele disse que poderia fazer minha mão parar de doer."],
  ["A","Talvez - ele me disse para continuar bebendo. Era horrível. Então eu comecei a me sentir estranha...."],
  ["P","Sim - eles sugeriram uma personalidade turbulenta, mas eu não estava particularmente preocupado até.... Eu comecei a perceber quão longe a imaginação dele tinha ído."],
  ["P","Sim - Jimmy disse que tinha feito algo para mim, então eu o segui para ver o que ele iria fazer."],
  ["P","Foi meu primeiro contato com o senso de humor do Jimmy."],
  ["P","Não era a medicação ideal, mas era tudo que eu tinha. Jimmy precisava de tratamento imediato; ele era perigoso."],
  ["P","Jimmy disse que eu usei o remo para bater nele. Eu jamais usaria violência contra um paciente, era ridículo! Mas a Rose acreditou nele."],
  ["P","Jimmy me acusou do pior crime possível. Ele pegou de uma história de jornal que ele tinha lido. Ele estava inventando tudo."],
  ["P","Eu experimentei com um varal, mas era muito fino. Ao invés disso achei uma corda. Eu ainda tinha minhas chaves do hotel então eu entrei escondido uma noite enquanto estava na condicional."],
  ["H","Isso saiu direto dele! Assim que achei o albúm de recortes eu sabia daonde Jimmy tinha pegado. Era o mesmo, até o último detalhe."],
  ["H","Jimmy tava sempre brincando com eletricidade. Engraçado que nunca era ele quem tomava choque."],
  ["H","Eu guardava aqueles tacos pra auto-defesa, mas eu estava enfurecido. Eu peguei um e fui pro quarto do Jimmy."],
  ["H","Jimmy era apegado em armas assim. Eu não tinha visto ele a noite toda depois que destruí as coisas dele. Eu devia ter adivinhado que ele tava trabalhando no seu próximo truquezinho."],
  ["H","Bem, se o Jimmy queria se esconder lá embaixo eu pensei que ele gostaria."],
  ["H","Ninguém se deu conta do quão longe Jimmy iria pra conseguir atenção."],
  ["H","Eu surtei. Estava com sangue nos olhos, eu odiava ele. Eu perdi o controle."],
  ["H","Nem era nem uma adaga! Mas eu nunca aprendi minha lição, Jimmy sempre tava um passo à minha frente."],
  ["R","Sim - esse era o ato do Jimmy no palco. Ele era comediante. Era bom, muito bom. As pessoas começaram a vir só para vê-lo."],
  ["R","Quebrar os espelhos foi só o começo. Eu perguntei à ele sobre isso mas ele não lembrava de ter feito nada disso. Então outras coisas estranhas começaram a acontecer."],
  ["R","Jimmy trancou ela em um dos quartos e a amarrou. Eu não sabia o que ele iria fazer. Eu encontrei ela e deixei ela ir. Jimmy disse que era uma piada! Ela não prestou queixa, mas contou aos jornais."],
  ["R","Jimmy odiava o que 'ele' fazia. Ele vinha lutando contra o Hugo Punch por toda sua vida. Estava dentro dele, fazendo ele cometer tantas coisas ruins. Jimmy não queria viver mais."],
  ["R","Sim - éramos casados. Nós éramos felizes no começo, antes das coisas mudarem."],
  ["R","Eu pensei que ter uma criança, iria resolver tudo. Eu estava errada."],
  ["R","Eu contei tudo para o Jimmy. Ele não lembrava do Hugo, ele bloqueou isso da memória. Hugo batia no Jimmy desde que ele nasceu, por 2 anos. Eu deveria ter impedido mais cedo."],
  ["R","Eu não tive escolha. Jimmy saiu para encontrar o túmulo do Hugo. Eu estava sozinha. Eu sabia o que tinha que fazer."],

],

subob:[

  ["Eu vi algumas maletas no baú. Há quem elas pertenciam?",
  "isso está conectado com o que você disse sobre as maletas?"],

  ["Eu encontrei alguns troféis. Quem ganhou eles?",
  "isso tem algo a ver com o que você disse sobre os troféis?"],

  ["De quem era essa bolsa de criança?",
  "isso está conectado com o que você disse sobre a bolsa?"],

  ["Eu vi uma garrafa de aguarrás e um isqueiro. Para quê eles serviam?",
  "isso tem alguma relação com o que você disse sobre o aguarrás e o isqueiro?"],

  ["De quem era a espada?",
  "Isso tem relação com o que você disse sobre a espada?"],

  ["Por que havia uma coleção de garrafas de whiskey em um dos quartos?",
  "isso tem relação com o que você disse sobre as garrafas de whiskey?"],

  ["Quem desenhou essas imagens violentas?",
  "isso tem relação com o que você disse sobre as imagens violentas?"],

  ["A quem pertencia o chapéu de Chef?",
  "isso tem algo a ver com o que você disse sobre o chapéu de Chef?"],

  ["Por que tem um pano manchado de sangue em uma das gavetas?",
  "isso tem relação com o que você disse sobre o pano manchado de sangue?"],

  ["De onde veio o frasco de Diazepam?",
  "isso tem relação com o que você disse sobre o Diazepam?"],

  ["De onde veio esse remo?",
  "isso está conectado com o que você disse sobre o remo?"],

  ["Eu vi um albúm de recortes com artigos de jornais nele. Quem fez?",
  "isso tem relação com o que você disse sobre o albúm de recortes?"],

  ["Por que tinha um varal amarrado em um rolo?",
  "isso tem relação com o que você disse sobre o varal amarrado no rolo?"],

  ["Por que tem um aquecedor antigo sinalizado como 'perigoso'?",
  "isso tem alguma relação com o aquecedor perigoso?"],

  ["Para que serviam os tacos de beisebol e criquete?",
  "isso tem relação com os tacos de beisebol e criquete??"],

  ["De onde veio aquela besta?",
  "isso tem relação com o que você disse sobre a besta?"],

  ["Para que serviam aquelas chaves enferrujadas?",
  "isso tem alguma relação com as chaves enferrujadas?"],

  ["Houve um incêndio no hotel?",
  "isso está conectado com o que você disse sobre o incêndio no hotel?"],

  ["A quem pertencia essa arma?",
  "isso tem relação com o que você disse sobre a arma?"],

  ["A quem pertencia a adaga?",
  "isso tem relação com o que você disse sobre a adaga?"],

  ["Quem é Hugo Punch?",
  "isso está conectado com o que você disse sobre o pôster do Hugo Punch?"],

  ["Como esses espelhos quebraram?",
  "isso está conectado com o que você disse sobre os espelhos quebrados?"],

  ["Para que servia essa bobina de fio?",
  "isso está conectado com o que você disse sobre a bobina de fio?"],

  ["Quem escreveu o bilhete de despedida?",
  "isso está conectado com o bilhete de despedida?"],

  ["A quem pertencia a aliança de casamento?",
  "isso está conectado com a aliança de casamento?"],

  ["De quem era o chocalho de bebê?",
  "isso tem algo a ver com o chocalho de bebê?"],

  ["Eu achei a Certidão de Nascimento do Jimmy. Nela diz que Hugo Hall é o pai verdadeiro do Jimmy.",
  "isso tem relação com o que você disse sobre a Certidão de Nascimento do Jimmy?"],

  ["Eu vi uma menina no porão, chorando. Quem era ela?",
  "",
  "Quando você disse que Jimmy roubou coisas de você,",
  "Quando você disse que Jimmy não era legal com a menininha,",
  "O que você me contou sobre a jovem garota que ficava no hotel,",
  "O que você disse sobre a jovem garota que era uma hóspede do hotel,"],

  ["Eu vi uma garotinha gritando com o Jimmy para ele devolver o brinquedo dela. Por que ele pegou?",
  "Eu vi você gritando com o Jimmy para ele devolver seu brinquedo. Por que ele pegou?",
  "O que você disse sobre o Jimmy estar roubando seu brinquedo,",
  "Quando você disse que roubar era o tipo de coisa que Jimmy fazia,",
  "",
  "Quando você disse que Jimmy não roubava coisas,"],

  ["Eu vi a garotinha, Amy, segurando um brinquedo em chamas. O que aconteceu?",
  "Eu vi você segurando um brinquedo em chamas. O que aconteceu?",
  "Você disse que não podia contar pra ninguém sobre sua mão ser queimada.",
  "O que você disse sobre o Jimmy pensar que botar fogo no brinquedo da Amy era uma piada,",
  "Você disse que a garotinha se queimou gravemente.",
  "Quando você disse que a garotinha continuou fazendo coisas perigosas e culpando o Jimmy,"],

  ["Eu vi a Amy fora de um quarto. Algo assustou ela. O que era aquilo?",
  "Eu vi você fora de um quarto. Algo te assustou. O que era?",
  "Quando você disse que precisava de um médico mas Jimmy te ameaçou para ficar,",
  "",
  "Quando você disse que a garotinha provavelmente estava com medo do Jimmy,",
  "Quando você disse que havia algo estranho sobre a garotinha,"],

  ["Eu vi Amy bebendo algo. Ela não parecia ter gostado. O que era?",
  "Eu vi você bebendo alguma coisa. Você não parecia gostar. O que era?",
  "Quando você disse que o remédio tinha um gosto horrível,",
  "O que você disse sobre a garotinha, Amy, bebendo álcool,",
  "",
  ""],

  ["Eu vi a garotinha no topo da escadaria, no corrimão. O que ela estava fazendo?",
  "Eu vi você no topo das escadas, no corrimão. O que você estava fazendo?",
  "Quando você disse que pensou que podia pular até o fundo das escadas,",
  "When you said Jimmy made the girl drink too much,",
  "Você disse que Amy tinha bebido uma garrafa de whiskey.",
  ""],

  ["Eu vi a Amy caída no final das escadas. O que aconteceu com ela?",
  "Eu vi você caída no final das escadas. O que houve com você?",
  "Você disse que não conseguia mais acordar.",
  "Você disse que a morte de Amy foi o motivo para a Rose ter contactado você.",
  "O que você disse sobre Jimmy estar por trás da morte da Amy,",
  "O que você disse sobre ser culpa da Amy ela ter morrido,"],

  ["Eu vi um homem batendo na porta, dizendo ao Jimmy que ele estava lá para ajudá-lo. Quem era?",
  "",
  "",
  "Quando você disse que Harvey estava preocupado com a mente do Jimmy,",
  "O que você disse sobre Jimmy estar além de qualquer ajuda,",
  "Você disse que o Dr Bose veio para ajudar o Jimmy."],

  ["Eu vi o Dr Bose segurando um animal morto por um cabo. O que aconteceu?",
  "Eu vi você segurando um animal morto por um cabo. O que aconteceu?",
  "",
  "Quando você disse que Jimmy teve um ideia de fazer algo legal para você,",
  "O que você disse sobre o Jimmy contar que encontrou o animal morto por aí,",
  "Quando você disse que não acreditava que Jimmy teria matado aquele animal,"],

  ["Eu vi Dr Bose fora da cozinha, conversando com o Jimmy. O que ele estava fazendo?",
  "Eu vi você fora da cozinha falando com o Jimmy. O que você estava fazendo?",
  "",
  "Quando você disse que não suspeitou que algo estava errado,",
  "Quando você disse que foi um erro o Dr Bose tentar ajudar o Jimmy,",
  "Quando você disse que Dr Bose estava tentando que o Jimmy fizesse coisas que ele não queria,"],

  ["Eu vi o Dr Bose cuspindo sangue. O que houve?",
  "Eu vi você cuspindo sangue. O que aconteceu?",
  "",
  "Quando você disse que precisava dar início ao tratamento do Jimmy com urgência,",
  "Quando você disse sobre as pegadinhas do Jimmy irem longe demais,",
  "Quando você disse que Dr Bose se feriu para culpar o Jimmy,"],

  ["Eu vi Dr Bose com uma seringa conversando com o Jimmy. O que ele estava fazendo?",
  "Eu vi você com uma seringa falando com o Jimmy. O que você estava fazendo?",
  "",
  "Quando você disse que Jimmy se negou a deixar você administrar o remédio,",
  "",
  "Você disse que o Dr Bose estava tentando medicar o Jimmy sem sua permissão."],

  ["Eu vi o Dr Bose tentando explicar o que aconteceu com o Jimmy. Ele parecia aflito. ",
  "Eu vi você tentando explicar o que aconteceu com o Jimmy. Você parecia aflito.",
  "",
  "Quando você disse que convenceu a Rose de que Jimmy estava inventando tudo,",
  "Quando você disse que Dr Bose estava certo em se preocupar sobre o que mais o Jimmy faria com ele,",
  "Quando você disse que decidiu dar uma outra chance ao Dr Bose,"],

  ["Eu vi o Dr Bose sentado na cama falando com o Jimmy. O que ele estava fazendo?",
  "Eu vi você sentado na cama conversando com o Jimmy. O que você estava fazendo?",
  "",
  "Você disse que Jimmy inventou outra mentira sobre você, uma muito pior.",
  "",
  "Quando você disse que nunca deveria ter confiado no Dr Bose,"],

  ["Eu vi o Dr Bose desolado, a polícia estava batendo na porta. O que estava acontecendo?",
  "Eu vi você desolado e escutei a polícia batendo na porta. O que estava acontecendo?",
  "",
  "Quando você disse que decidiu tomar o controle de uma vez por todas,",
  "Você disse que não acreditava na história do Jimmy sobre o Dr Bose.",
  "Quando você disse que Dr Bose merecia ser preso,"],

  ["Eu vi o Dr Bose amarrando uma corda em volta do pescoço. Ele se matou. Por quê?",
  "Eu vi você amarrando uma corda em seu pescoço. Você se suicidou. Por quê?",
  "",
  "Você disse que queria que aquilo tudo parasse.",
  "Quando você disse que Dr Bose foi levado à se matar,",
  "Quando você disse que Dr Bose fez a coisa certa,"],

  ["Eu vi um homem dizendo que Jimmy tinha mentido sobre o ataque. Quem era ele?",
  "",
  "",
  "Quando você disse que Harvey sabia que Jimmy estava mentindo,",
  "Quando você disse que ouviu aquela história antes em algum lugar,",
  "Quando você disse que Harvey estava errado em não acreditar na história do Jimmy,"],

  ["Eu vi o Harvey gritando, dizendo para o Jimmy admitir que mentiu. Ele admitiu?",
  "Eu vi você gritando, dizendo ao Jimmy que admitisse que mentiu. Ele admitiu?",
  "",
  "O que você disse sobre o Jimmy nunca admitir suas mentiras,",
  "Quando você disse que Jimmy começou a montar armadilhas para você,",
  "Você disse que Harvey estava errado em implicar com o Jimmy."],

  ["Eu vi Harvey sofrendo um choque elétrico. O que houve?",
  "Eu vi você sofrendo um choque elétrico. O que aconteceu?",
  "",
  "",
  "Quando você disse que decidiu destruir as coisas dele,",
  "Você disse que Harvey deveria ter jogado aquele aquecedor estragado fora."],

  ["Eu vi Harvey com um taco, saindo de um quarto. O que ele fez?",
  "Eu vi você com um taco, saindo de um quarto. O que você fez?",
  "",
  "Quando você disse que violência só piora as coisas.",
  "Quando você disse que Jimmy logo iria se vingar,",
  "O que você disse sobre Harvey não conseguir controlar sua raiva,"],

  ["Eu vi o Harvey ser atingido na perna por uma flecha. O que houve?",
  "Eu vi você ser atingido na perna por uma flecha. O que aconteceu?",
  "",
  "",
  "Quando você disse que achou que Jimmy gostava de se esconder no porão,",
  "Quando você disse que Jimmy não usaria uma arma daquele jeito,"],

  ["Eu vi o Harvey trancando o Jimmy no porão. O que houve?",
  "Eu vi você trancando o Jimmy no porão. O que aconteceu?",
  "",
  "",
  "Você disse que estava errado em achar que Jimmy não poderia causar nenhum dano no porão.",
  ""],

  ["Eu vi um incêndio no porão. O que aconteceu com o hotel?",
  "Eu vi um incêndio no porão. O que aconteceu com o hotel?",
  "",
  "",
  "Quando você disse que queria o Jimmy fosse embora,",
  "Você disse que o incêndio no hotel foi um acidente."],

  ["Eu vi o Harvey com uma arma, praticando com ela. O que ele estava fazendo?",
  "Eu vi você com uma arma, praticando com ela. O que você iria fazer?",
  "",
  "Você disse que Harvey não conseguia controlar sua raiva.",
  "Quando você disse que não imaginou que Jimmy se armaria também,",
  "Quando você disse que Harvey não deveria manter uma arma no hotel,"],

  ["Eu vi Harvey indo em direção ao salão com uma arma. O que ele estava fazendo?",
  "Eu vi você indo em direção ao salão com uma arma. O que você estava fazendo?",
  "",
  "",
  "Quando você disse que estava procurando pelo Jimmy,",
  ""],

  ["Eu vi o Harvey sendo esfaqueado nos bastidores. O que houve?",
  "Eu vi você ser esfaqueado nos bastidores. O que houve?",
  "",
  "",
  "Quando você disse que Jimmy sempre ganhava no final,",
  "Quando você disse que Jimmy estava apenas se defendendo,"],

  ["Eu vi uma moça explicando que a adaga era um abridor de cartas. Quem era ela?",
  "",
  "",
  "",
  "Você disse que a Rose defendeu o Jimmy até o fim.",
  "Quando você disse que a policial entendeu que Jimmy agiu em legítima defesa"],

  ["Quem a Rose estava cumprimentando na recepção?",
  "Quem você estava cumprimentando na recepção?",
  "",
  "",
  "Quando você disse que eles pensaram que você tinha tentado atirar no Jimmy,",
  "Quando você disse que Jimmy encontrou um meio de trazer mais hóspedes,"],

  ["Eu vi a Rose anunciando Hugo Punch para o palco.",
  "Eu vi você anunciando Hugo Punch para o palco.",
  "",
  "",
  "",
  "O que você disse sobre Jimmy se encarando e ficando nervoso,"],

  ["Eu vi a Rose em um corredor cheio de manequins. Quem botou eles lá?",
  "Eu vi você parada em um corredor cheio de manequins. Quem colocou eles lá?",
  "",
  "",
  "",
  "O que você disse sobre Jimmy não estar no controle mais,"],

  ["Eu vi a Rose no salão. O público estava vaiando e ela estava se desculpando. O que estava acontecendo?",
  "Eu vi você no salão. O público estava vaiando e você se desculpando. O que estava acontecendo?",
  "",
  "",
  "Você disse que Jimmy estragaria tudo eventualmente.",
  "Quando você disse que Jimmy perdeu a paciência e fez algo estúpido,"],

  ["Eu vi a Rose chateada e pessoas batendo na porta fazendo perguntas. Quem eram elas?",
  "Eu vi você chateada porque as pessoas estavam batendo na porta e fazendo perguntas. Quem eram elas?",
  "",
  "",
  "",
  "Quando você disse que Jimmy queria deixar tudo para trás e ir embora,"],

  ["Eu vi a Rose em um quarto no andar de cima. Pareceu que ela encontrou alguém no banheiro. O que houve?",
  "Eu vi você em um quarto do andar de cima. Me pareceu que você encontrou alguém no banheiro. O que aconteceu?",
  "",
  "",
  "",
  "Quando você disse que tinha que contar a verdade ao Jimmy,"],

  ["Eu vi a Rose com um taco de madeira, atacando alguém. Quem era?",
  "Eu vi você com uma taco de madeira, atacando alguém. Quem era?",
  "",
  "Você disse que a Rose tinha um passado sombrio.",
  "Você disse que haviam coisas que Rose nunca tinha te contado.",
  "Quando você disse que não conseguiria viver com você mesma,"],

  ["Eu vi a Rose, ela estava em chamas. O que aconteceu?",
  "Eu vi você, você estava em chamas. O que aconteceu?",
  "",
  "",
  "",
  "Quando você disse que pediu ao Jimmy para mostrar aonde o Hugo morava,"],

  ["Eu vi alguém no palco. Um intérprete, se anunciando como O Grande Hugo.",
  "",
  "",
  "",
  "Quando você disse que Hugo foi o primeiro marido da Rose,",
  "Quando você disse que as coisas evoluíram com o Hugo,"],

  ["Eu escutei um homem gritando com alguém, dizendo para fazer como ele mandava. Quem era esse alguém?",
  "",
  "",
  "",
  "",
  "Você disse que havia apenas uma coisa que poderia dar ao Hugo."],

  ["Eu ouvi um homem gritando e uma criança chorando. O que houve?",
  "",
  "",
  "",
  "",
  "Você disse que Jimmy é filho do Hugo."],

],

subs:[

  "INTRO",[
   13.6,5,"Jimmy!",14.6,4,"",
   16.2,4,"Jimmy!",17.4,4,"",
   18.8,2,"Jimmy!",20,4,"",
   20.1,6,"VOZES VINDO DO ALTO-FALANTE",21.6,6,"",
   24.3,3,"Apenas me deixe em paz...",25.9,4,"",
   26.5,6,"SOLUÇANDO",27.9,4,"",
   28.6,6,"AS VOZES ECOAM MAIS ALTO",30.3,4,"",
   30.7,3,"Pare com isso!",31.8,4,"",
   32.4,3,"Por favor, apenas me deixe em paz!",34.8,4,"",
   35.8,6,"VOZES ATRAVÉS DO RUÍDO",37.3,4,"",
   44.5,6,"TELEFONA TOCA",45.6,0,"",
   46.6,1,"Oi?",47.6,0,"",
   47.7,3,"Maya? É a Hannah.",48.8,0,"",
   49.4,1,"Hannah? Onde você está??",51.2,0,"",
   51.3,1,"Vocês foram embora e me deixaram para trás!",53.6,0,"",
   53.7,1,"Onde você está agora? Que número é esse?",55.6,0,"",
   55.7,3,"Nós reservamos um hotel perto da estrada.",57.4,0,"",
   57.5,3,"Está muito longe?",58.8,0,"",
   58.9,1,"Eu não sei. Vou ter que ligar quando chegar lá.",61.1,0,"",
   61.2,3,"Você não pode, não há sinal.",62.9,0,"",
   63,1,"Então... ",64.1,1,"",
   65,1,"Não importa. Vai para a cama Hannah.",67,0,"",
   67.1,3,"Ouve. Certifique que você est...",68.3,0,"",
   68.6,6,"A CHAMADA CAI",70.1,0,"",
   71,6,"CHAMADA TERMINADA",72.5,0,"",
   84,6,"JAZZ DOS ANOS 1950 TOCANDO NA RÁDIO",85.5,4,"",
   92.1,3,"Maya, eu presumo?",94.1,0,"",
   94.5,3,"Oh, não se assuste.",96.4,0,"",
   96.6,3,"Os seus amigos reservaram por você...",99,0,"",
   99.1,3,"Deixe so eu ver aqui.",100.8,0,"",
   101.8,3,"Ah. Sim.",102.8,0,"",
   102.9,3,"Quarto 101.",104,0,"",
   104.2,3,"Está tudo pago por isso não precisa se preocupar com nada.",107.2,0,"",
   107.3,3,"Você tem amigos legais.",109.1,0,"",
   109.9,3,"Bem legais.",111.2,0,"",
   111.5,3,"E há muitos de vocês, pelo que vejo..",115.6,0,"",
   116.2,3,"Fico feliz por ver tantos...",118.2,0,"",
   118.3,3,"Rostos jovens e frescos, para variar.",122.7,0,"",
   123.5,3,"Er... você está aqui para o festival de música eu presumo?",126.8,0,"",
   127.3,1,"Sim, era suposto acamparmos lá essa noite, mas...",130.5,0,"",
   130.6,3,"Está um tempo horrível para isso.",133.1,0,"",
   136,3,"Você vai ficar para café da manhã?",137.5,0,"",
   137.6,1,"Acho que não, É provável sairmos.",140.2,0,"",
   140.3,3,"Está bem. E se não se importe que eu pergunte, Maya,",143.7,0,"",
   143.8,3,"você estaria interessada no entretenimento desta noite?",147.5,0,"",
   147.9,1,"Esta noite??",148.9,0,"",
   149,3,"Er, começa perto da meia noite normalmente.",152.1,0,"",
   152.6,3,"Na verdade, sou eu que estou fazendo isso, comédia.",155.8,0,"",
   155.9,3,"Eu faço esse personagem de comédia chamado Hugo Punch,",161,0,"",
   161.1,3,"Ele é tipo um sociopata cômico,",164.8,0,"",
   164.9,3,"Ele diz coisas que você não deveria dizer e esse tipo de coisa.",169.6,0,"",
   169.7,3,"É bastante popular com os estudantes.",171.7,0,"",
   172.3,1,"Acho que não, nós vamos apenas para a cama.",175.7,0,"",
   175.8,3,"Tem a certeza não te posso convencer a ficar?",179.2,0,"",
   179.5,1,"Tudo bem, eu prefiro ir para a cama. Desculpe.",182.8,0,"",
   182.9,3,"Tudo bem, tudo bem, tudo bem...",185.4,0,"",
   185.6,1,"Por que lado são os quartos?",186.7,0,"",
   187.2,3,"Erm usa o elevador, você fica no primeiro piso.",190.2,0,"",
   190.3,1,"OK valeu.",191.6,0,"",
   193.1,3,"Ah, Maya, deixe sua chave na caixa amanhã por favor.",198.1,0,"",
   198.2,1,"OK!",199.2,0,"",
   199.3,6,"PORTAS DO ELEVADOR FECHAM",200.8,0,"",
   204.4,3,"Melhor show da cidade e ninguém interessado.",207.2,0,"",
   210.3,3,"Quem precisa de entretenimento de verdade quando você tem 'You Tune' e 'My Face' e o que mais for.",216.6,0,"",
   216.7,3,"Estúpidos, incultos...",218.7,0,"",
   218.8,5,"Hugo não gosta de crianças mal-educadas, elas são travessas.",223,0,"",
   225.5,3,"Não comece com isso de novo.",227.3,0,"",
   231.1,3,"Eu não quero ouvir isso, tá bom? Esta noite não.",234.2,0,"",
   237,5,"Crianças travessas são ovos podres. Elas precisam aprender uma lição!",240.9,0,"",
   254.2,3,"Cala a boca! Cala a boca agora!",256.5,0,"",
   257.3,3,"Você faz sempre isto, são clientes pagantes!.",260.2,0,"",
   260.5,3,"Eles não fizeram nada a você.",262.4,0,"",
   263.3,3,"Deixa eles em paz.",265.4,0,"",
   266.2,5,"Ovos podres precisam ser quebrados! Quebre-os com força e rache a casca deles,",269.3,0,"",
   269.5,5,"Chute-os escada abaixo para o Inferno!",272.3,0,"",
   272.8,5,"Você sabe o que tem de fazer Jimmy.",275,0,"",
   275.6,5,"Mostre a eles quem é o chefe.",277.7,0,"",
   278.9,5,"É assim que se faz!",281.1,0,"",
   293.3,6,"GRITO DISTANTE",294.9,0,"",
   308,6,"HOMEM DÁ RISADA",309.6,0,"",
   310,3,"Isso mesmo, vá dormir....",313,0,"",
   345.2,6,"TELEFONE ESTALA",346.9,0,"",
   358.5,6,"VOZ DO ALTIFALANTE",361.9,0,"",
   362,1,"Vá embora do hotel!",363.6,0,"",
   363.7,1,"Sai enquanto podes!",365.7,0,"",
   367.6,1,"Você tem de descobrir o que ele fez...",369.3,0,"",
   369.4,1,"...e contar a todo o mundo.",371.3,0,"",
   371.4,1,"Faça ele perceber o que fez!",373.3,0,"",
   373.5,6,"VOZ SE TRANSFORMA EM RUÍDO",376,0,"",
   420,1,"",420.9,0,"X",
],
  "A2",[
   0.8,1,"Jimmy, devolve isso! Isso é meu!",2.9,0,"",
   3,1,"Para de roubar minhas coisas!",4.3,0,"X",
],
  "A3",[
   0.7,6,"GRITOS",2,0,"X",
],
  "A4",[
   1.1,1,"Estou te falando Jimmy, não pode fazer isso!",3.1,0,"",
   3.2,1,"Você é horrível...",4.7,0,"X",
   3.8,6,"A VOZ DESVANECE",4.4,0,"X",
],
  "A5",[
   3.8,6,"TOSSE",4.8,0,"X",
],
  "A6",[
   4.2,6,"RISADAS",5.2,0,"X",
],
  "P1",[
   3.8,6,"BATIDAS",4.8,0,"",
   5.8,2,"Jimmy?",6.8,0,"",
   7.2,2,"Sou o Doutor Bose.",8.9,0,"",
   9,2,"Estou aqui para ter uma pequena conversa, OK?",11.5,0,"",
   14.5,2,"Obrigado Jimmy, Não demorarei muito tempo.",16.6,2,"X",
],
  "P3",[
   1,2,"Isso é uma ótima ideia, Jimmy!",3.4,0,"",
   3.5,2,"Tenho a certeza que você será um ótimo cozinheiro um dia.",5.7,0,"",
   5.8,2,"Por que você não traz isso para mim quando terminar?",8,0,"",
   8.1,2,"Vou esperar aqui por você, tabom?",9.8,0,"X",
],
  "P4",[
   3,6,"SONS DE ALGUÉM ENGASGANDO",4,0,"",
   7.6,2,"Jimmy!",8.6,0,"X",
],
  "P5",[
   1.2,2,"Isto não vai doer Jimmy.",2.9,0,"",
   3,2,"Tudo o que você tem que fazer é ficar quieto e parar de se mover!",6.6,0,"X",
],
  "P6",[
   0.6,2,"Eu nunca usaria força dessa maneira em um paciente, Sra. Hall.",4.8,0,"",
   4.8,2,"Isso vai contra tudo o que eu acredito.",7.3,0,"",
   7.4,2,"Você tem que entender, ele está inventando tudo!",10,0,"X",
],
  "P7",[
   1.1,2,"Você não pode fugir de mim tão facilmente, Jimmy.",3.9,0,"",
   4,2,"Acho que devemos começar de novo, não acha?",6.5,0,"",
   6.6,2,"Por que você não faz o que eu peço desta vez?",8.7,0,"",
   8.8,2,"Isso seria um bom começo, não seria?",11,0,"X",
],
  "P8",[
   0.6,2,"É a polícia, Sr Bose.",2.1,0,"",
   2.2,2,"Preciso que você venha até a delegacia.",4.1,0,"",
   4.4,2,"Pode abrir a porta por favor?",5.8,0,"X",
],
  "P9",[
   14.1,6,"SONS DE ALGUÉM ENGASGANDO",15.5,0,"",
   15.9,6,"ALARME DO ELEVADOR TOCANDO",16.9,0,"X",
],
  "H1",[
   0.8,3,"Ele inventou isso. Estou te dizendo, ele tem mentindo sobre tudo,",3.4,0,"",
   3.5,3,"Provavelmente mentiu sobre as outras coisas também.",5,0,"",
   5.1,4,"Não seja ridículo! Ele não mentiria sobre algo assim!",7.3,0,"",
   7.4,3,"Tem certeza?",8.3,0,"",
   8.4,3,"Ele mente sobre tudo! Abra a porra dos olhos Rose!",11.4,0,"",
   11.5,3,"Ah, é isso mesmo! Vá embora!",12.8,0,"",
   12.9,4,"Não estou ouvindo Harvey, você só está implicando com eleProvavelmente mentiu sobre as outras coisas também.",14.7,0,"",
   14.9,3,"É a verdade!",16.2,0,"X",
],
  "H2",[
   1.5,6,"BATIDAS NA PORTA",2.4,0,"",
   2.5,3,"Jimmy?",3.5,0,"",
   4.3,3,"Eu sei que você está me ouvindo!",5.8,0,"",
   6.2,3,"Eu sei que você inventou sua historinha sobre aquele psiquiatra.",10,0,"",
   10.1,3,"Eu sei de onde você tirou isso!",11.6,0,"",
   12,3,"Eu sabia que já tinha lido isso antes, está no seu maldito albúm de recortes!",15.3,0,"",
   16.1,3,"Venha cá!",17.3,0,"",
   18.3,3,"Jimmy!",19.6,0,"X",
],
  "H3",[
   1.2,6,"FAÍSCAS ELÉTRICAS",2.2,0,"",
   2.3,6,"GRITOS DE DOR",3.3,0,"",
   7.2,3,"Jimmy!",8.2,0,"X",
],
  "H4",[
   1,6,"COISAS QUEBRANDO",2,0,"X",
],
  "H5",[
   0.8,6,"GRITOS DE DOR",1.9,0,"",
   4.1,3,"Jimmy!",5.1,0,"X",
],
  "H6",[
   1.3,3,"Você pode ficar aí dentro esta noite, Jimmy!",3.7,0,"",
   3.8,3,"Eu já tive o bastante.",5,0,"",
   5.1,6,"BATIDAS NA PORTA",6.6,0,"X",
],
  "H7",[
   0.3,6,"ALARME DE INCÊNDIO",1.8,0,"",
   2.7,3,"Jimmy não seja burro, abra a porta!",4.9,0,"",
   5.2,3,"Você vai morrer se ficar aí, seu idiota! Abra a porta!",8.4,0,"X",
],
  "H8",[
   2.7,3,"Vá embora do hotel Jimmy.",4.6,0,"",
   6.6,3,"Embora do meu hotel...",8,0,"",
   8.6,3,"Esse é meu hotel. Vá embora do meu hotel Jimmy.",12,0,"X",
],
  "H9",[
   1.8,3,"Vá embora do meu hotel.",3.2,0,"",
   3.3,3,"Este é o MEU hotel.",5,0,"X",
],
  "R1",[
   0.8,8,"O Harvey iria atirar no Jimmy.",2.4,0,"",
   2.5,8,"Era apenas um abridor de cartas. Foi legítima defesa! Olhe!",5.9,0,"X",
],
  "R2",[
   3.5,4,"Jimmy",4.5,0,"X",
],
  "R3",[
   1.2,4,"Senhoras e senhores.",2.4,0,"",
   2.5,4,"Por favor, recebam no palco,",3.9,0,"",
   4,4,"seu entretenimento desta noite,",5.9,0,"",
   6,4,"Sr Hugo Punch!",8,0,"",
   8.1,6,"MÚSICA E APLAUSOS",9.6,0,"X",
],
  "R4",[
   0,4,"",0,0,"",
],
  "R5",[
   0.7,4,"É só o número de comédia dele.",2.6,0,"",
   2.7,4,"É o senso de humor dele!",4.4,0,"",
   4.5,4,"Desculpe se você se sentiu ofendido...",6.3,0,"",
   6.4,4,"Com licença...",7.6,0,"X",
],
  "R6",[
   0.5,6,"BATIDAS NA PORTA DA FRENTE",1.8,0,"",
   1.9,4,"Sra Hall?",3.4,0,"",
   4.2,4,"Sra Hall, Podemos conversar, por favor?",6.5,0,"X",
],
  "R7",[
   1.4,4,"Jimmy?",2.4,0,"",
   4.1,6,"GRITOS",5.1,0,"",
   5.2,4,"Jimmy! O que vocè fez! Jimmy!",8,0,"X",
],
  "R8",[
   0.5,6,"CRIANÇA CHORANDO",1.5,0,"",
   1.6,5,"Você vai fazer o que eu mandar! Entendeu?",4.2,0,"",
   4.3,5,"Estúpido insignificante!",5.4,0,"",
   5.5,6,"CRIANÇA SENDO ESBOFETEADA",6.7,0,"",
   6.9,6,"HOMEM SENDO ATINGIDO POR UM TACO",8.3,0,"X",
],
  "R9",[
   1.4,6,"GRITOS",2.9,0,"X",
],
  "V1",[
   5.5,7,"Contemplem!",6.3,0,"",
   6.4,6,"GONG",7.4,0,"",
   7.5,7,"Eu sou O Grande Hugo!",10.2,0,"",
   11.9,7,"Eu me ergo sozinho acima de todos os outros.",15.9,0,"",
   17.4,7,"Eu sou a luz que ilumina a escuridão.",21.4,0,"",
   22.7,7,"Somente eu sou o mestre.",26.5,0,"X",
],
  "V2",[
   5,6,"MULHER SOLUÇANDO",6.5,0,"",
   8,5,"Não compre nada sem a minha permissão.",10.5,0,"",
   10.6,6,"VIDRO QUEBRANDO",11.5,0,"",
   11.6,5,"Eu não vou deixar você arruinar a minha vida!",14,0,"",
   14.1,6,"MAIS COISAS QUEBRANDO",15.2,0,"",
   15.1,5,"A tua vida não significa nada!",16.8,0,"",
   16.9,5,"Entende o que eu tô falando?",18.6,0,"",
   18.7,6,"BARULHOS DE ALGO QUEBRANDO E MULHER GRITANDO",20.9,0,"X",
],
  "V3",[
   3.1,6,"CRIANÇA CHORANDO",4.6,0,"",
   9,5,"Sente e sossegue!",10,0,"",
   10.1,6,"SOM DE CHICOTE",11.4,0,"",
   11.5,5,"Seu estúpido insignificante!",12.8,0,"",
   12.9,5,"Faça o que eu mandar!",14.9,0,"",
   15,6,"MULHER GRITANDO<br>Não!",17,0,"X",
],
  "EPI",[
   17.9,3,"Senhoras e senhores,",19,0,"",
   19.1,3,"Por favor, recebam no palco,",20.6,0,"",
   20.7,3,"seu entretenimento para esta noite,",22.5,0,"",
   22.6,3,"Sr Hugo Punch!",24.7,0,"",
   24.8,6,"APLAUSOS",26.4,0,"",
   33.5,5,"Maya!",34.5,0,"",
   36.1,5,"Maya!",37.1,0,"",
   40.5,5,"Maya?",41.5,0,"",
   42,5,"Maya!",43.5,0,"",
   44,6,"SOLUÇOS",46,0,"",
   47.5,3,"Para, para, para, para...",49.9,0,"",
   50,3,"Para com isso.",51.5,0,"",
   52.6,3,"Por que você continua me forçando a fazer essas coisas?",55.3,0,"",
   56,3,"Por favor, só para.",57.5,0,"",
   58.4,3,"Por favor, só para, para isso...",60.4,0,"",
   63.2,5,"Você sempre vai fazer isso, Jimmy.",64.9,0,"",
   66.7,5,"Eu estou no comando.",68.6,0,"",
   68.7,5,"Você não.",69.7,0,"",
   71,5,"Eu estou no comando.",73.5,0,"",
],
  "BRO",[
   1.5,5,"Bem-vindo ao túmulo do Hugo!",5.5,5,"",
   5.6,5,"O segredinho da mamãe.",8.9,5,"",
   9,5,"Ela misturou o concreto sozinha, sabia?",11.8,5,"",
   11.9,5,"e então derramou sobre o corpo dele",15.1,5,"",
   15.2,5,"e ficou observando endurecer.",17.8,5,"",
   18.1,5,"Ela achou que se tinha livrado dele.",21,5,"",
   21.3,5,"Mas ela não percebeu, Maya.",24.7,5,"",
   24.8,5,"Entenda, o Hugo é apenas um de nós.",29.1,5,"",
   29.2,5,"Apenas mais um tronco na fogueira.",33,5,"",
   33.2,5,"Ele se queimou.",35.8,5,"",
   36,5,"Mas o fogo tem queimado os corredores por séculos.",41.2,5,"",
   41.3,5,"Limpando o caminho...",43.5,5,"",
   43.6,5,"Iluminando a escuridão...",45.9,5,"",
   46,5,"devastando os velhos, os pobres e os fracos.",52.3,5,"",
   52.4,5,"E está queimando em você tambem, Maya.",56.7,5,"",
   56.8,5,"Eu posso ver!",58.8,5,"",
   59,5,"Estamos destinados a ficar juntos, você e eu.",62.9,5,"",
   63,5,"Você é quem eu sempre esperei.",66.6,5,"",
   66.8,5,"É por isso que não posso deixar você sair.",71,5,"",
   71.1,5,"Você vai ficar aqui comigo, Maya.",75.2,5,"",
   75.3,5,"Para semmpre.",77.5,5,"X",
],
  "COR",[
   0.2,5,"Falando com os mortos, Maya?",4.3,1,"",
   4.5,1,"Eu sei que o Hugo é o seu pai, Jimmy.",6.6,1,"",
   6.7,1,"Eu achei a sua certidão de nascimento, também sei que a Rose tentou matar ele.",10.5,1,"",
   10.6,5,"Mas ela falhou, nao foi?",13.6,1,"",
   13.7,1,"Então onde está ele agora?",15.5,1,"",
   15.8,6,"RISADAS",17,1,"",
   20.3,5,"Bem, então porque você não vem conhecer ele?",22.8,1,"",
   22.9,5,"Está na hora de eu te apresentar a família, Maya.",27.8,1,"",
   27.9,6,"RISADAS",29,1,"X",
],
  "AP",[
   2.6,5,"Oi Maya!",5,1,"",
   6.5,5,"Maya!",7.5,5,"",
   9,5,"Maya!",10.3,5,"",
   10.4,6,"BATIDAS NA PORTA",11.4,5,"",
   11.9,5,"Você não pode fugir, Maya!",14.9,5,"",
   15,5,"Abre a porta!",16.2,5,"X",
],
  "TUT",[
   0.83,1,"A SITUAÇÃO",
   4.33,1,"",
   6.4,1,"Esse é o Jimmy Hall o proprietário",
   9.3,1,"E Psicopata perigoso",
   12.37,1,"",
   15.27,1,"Ele tem planos obscuros para os amigos da Maya",
   18.3,1,"",
   19.4,1,"A Maya escapou",
   22.4,1,"",
   24.23,1,"Jimmy sabe que a tem de parar",
   27.33,1,"",
   27.83,1,"A PERSEGUIÇÃO",
   31.57,1,"",
   33.3,1,"Jimmy se esconde onde quer que consiga",
   36.8,1,"",
   39.37,1,"Em cantos",
   41.63,1,"",
   42.33,1,"Nas sombras",
   44.33,1,"",
   45.27,1,"Esperando você chegar",
   47.6,1,"",
   48.23,1,"Ou se aproximando sorrateiramente por trás de você",
   50.57,1,"",
   51.2,1,"Ele não se pode esconder nas escadas",
   53.53,1,"",
   54.33,1,"nem no térreo",
   56.47,1,"",
   57.33,1,"nem no porão",
   60.27,1,"",
   60.7,1,"ESTRATÉGIA",
   64.67,1,"",
   66.17,1,"Se o Jimmy ver você, foge",
   67.67,1,"Para fora do seu campo de visão",
   71.83,1,"",
   75.13,1,"Pode se esconder em qualquer quarto destrancado",
   78.17,1,"",
   79.67,1,"Se o Jimmt entrar",
   81.73,1,"",
   84.13,1,"Se esconde num armário",
   86.4,1,"",
   90.2,1,"ou no banheiro",
   92.33,1,"",
   94.73,1,"Use o olho mágico nos quartos de hóspedes",
   97.67,1,"",
   98.53,1,"Para ver se o jimmy está lá fora",
   101.43,1,"",
   103.63,1,"Chama por ele para o atrair",
   105.2,1,"",
   106.67,1,"Para controlar onde ele vai",
   109.67,1,"",
   110.23,1,"Ache chave de quartos nas gavetas",
   112.67,1,"",
   114.17,1,"Tranca o Jimmy fora dos quartos",
   116.4,1,"",
   117.83,1,"Ou tranca ele dentro",
   120.13,1,"Se escapares primeiro",
   123.17,1,"",
   124.67,1,"Examina os quartos rapidamente usando a fechadura",
   127.7,1,"",
   129.67,1,"OS MORTOS",
   133.5,1,"",
   135.17,1,"Jimmy tem um passado ensanguentado",
   138.2,1,"As suas vítimas nunca sairam",
   141.17,1,"Elas ainda assombram o hotel",
   144.47,1,"",
   145.67,1,"Usa o receptor para falar com elas",
   150.2,1,"",
   153.23,1,"Pergunte sobre coisas que elas viram e descobre a história",
   159.07,1,"",
   159.13,1,"Perguntar sobre assuntos importante vai fazer eles aparecerem",
   166.63,1,"",
   168.17,1,"Depois segue as luzes piscando",
   171.1,1,"E ouve os barulhos estranhos",
   174.07,1,"",
   175.47,1,"Use a bússola para te guiar",
   178.4,1,"",
   180.07,1,"Quando estiver perto, continue olhando ao redor",
   183.07,1,"Ou fique parado e olhe em frente",
   186.17,1,"",
   186.7,1,"TALENTO DA MAYA",
   191.5,1,"",
   192.5,1,"Maya pode ver o submundo",
   196.5,1,"",
   197.97,1,"Vá para um lugar com pouca luz",
   200.43,1,"",
   201.43,1,"E então use o espelho",
   204.67,1,"",
   206.27,1,"você verá: A localizaçáo de itens importantes...",
   209.2,1,"A localização dos espiritos...",
   212.23,1,"Conexões entre espiritos e itens",
   217.23,1,"",
   218.3,1,"Às vezes, o Jimmy rouba alguns de seus itens se te apanhar",
   222.77,1,"",
   224.27,1,"Procure pelo seu receptor no depósito do primeiro andar (perto das escadas)",
   229.3,1,"",
   230.27,1,"Procure bússolas e chaves nos quartos de hóspedes",
   234.77,1,"",
   236.23,1,"Veja as instruções do receptor para mais dicas em como caçar fantasmas",
   241.47,1,"",
],
],

itexts:[

  "algumas malas antigas",
  "alguns troféus e prêmios",
  "uma bolsa de criança",
  "uma garrafa de aguarrás e um isqueiro",
  "uma espada ornamental",
  "algumas garrafas de whiskey e outras bebidas alcoólicas",
  "alguns desenhos infantis violentos",
  "um chapéu de chef",
  "um pano velho manchado em sangue",
  "uma seringa e um frasco de Diazepam",
  "um velho remo ou batedor",
  "um albúm de recortes de artigos de jornal",
  "um varal e um rolo de massa",
  "um aquecedor antigo marcado como 'perigoso'",
  "alguns tacos de críquete e beisebol",
  "uma besta",
  "algumas chaves enferrujadas",
  "algumas fotos de fumaça saindo do hotel",
  "uma pistola antiga",
  "uma adaga ornamental",
  "um pôster do show cômico de Jimmy Hall",
  "alguns espelhos de parede quebrados",
  "uma bobina de fio de cobre",
  "um bilhete escrito a mão dizendo 'adeus'",
  "um anel em sua caixinha",
  "um chocalho de bebê",
  "a certidão de nascimento de Jimmy Hall",

],

ketex:[

  "Chave Para O Quarto ",
  "Você anotou: ",
  "Você anotou '",
  "Você pegou: ",
  "Você pegou a chave para o quarto ",
  "Uma Bússola",
  "Um Espelho Da Previsão",

],

patex:[

  ["H","Pertenciam a Rose, mas ele nunca usou.","R","[As maletas] eram minhas. Eu queria ir embora, mas nunca tive a chance."],
  ["R","Jimmy comprou [os troféis], para parecer que ele havia ganhado eles."],
  ["A","[A bolsa] era minha. Ganhei no meu aniversário, mas foi roubada.","H","Era a bolsa daquela menina, pobrezinha.","R","[A bolsa] pertencia a garotinha."],
  ["A","Eu não sabia o que [o aguarrás e isqueiro] eram, até o Jimmy me mostrar.","P","Melhor você perguntar ao Jimmy.","H","[O aguarrás e isqueiro] eram meus, mas eu não guardava eles juntos.","R","[O aguarrás e isqueiro] pertenciam ao Harvey."],
  ["A","Jimmy tinha [a espada]. Eu não gostava daquilo.","P","Eu vi o Jimmy brincando com [a espada]. Eu pensei que era perigoso.","H","A gente tinha um mostruário de armas medievais. Jimmy furtou [a espada].","R","[A espada] pertencia à um conjunto de armadura que tínhamos. Mas ela desapareceu."],
  ["A","Eu não sei [de onde as garrafas vieram], mas crianças não deveriam beber álcool.","P","[As garrafas] provavelmente eram do bar.","H","Eu não lembro [daonde as garrafas vieram], mas não tem nada de errado em tomar um gole.","R","Harvey deve ter colocado [as garrafas] lá."],
  ["A","O menino costumava desenhar [imagens violentas].","P","Jimmy costumava desenhar [imagens violentas].","H","Quem você acha que [desenhou as imagens violentas]? Jimmy! Ele tinha uma imaginação muito agressiva, o pequeno Jimmy.","R","Jimmy costumava desenhar imagens [violentas] sobre a guerra. Ele era como outros garotos."],
  ["P","Jimmy achou [o chapéu do Chef] e o vestiu.","H","Era do Chef, quem mais usaria gorro de Chef?","R","Nosso Chef costumava usar [o chapéu de Chef]."],
  ["A","[O pano] poderia ser meu.","P","[O pano] era meu. Eu guardei, no caso de precisar de evidência.","H","[O pano] talvez tinha a ver com o doutor."],
  ["P","[O medicamento] pode ajudar a tratar comportamento impulsivo, em algumas pessoas.","H","Provavelmente o doutor deixou [o remédio].","R","[O medicamento] pertencia ao Doutor Bose."],
  ["P","Não sei, mas Jimmy Achou [o remo].","H","[O remo] tava sempre atrás da bancada na recepção. Sei lá da onde veio.","R","[O remo] pertencia ao meu marido."],
  ["A","Jimmy fez [o albúm de recortes]. Não sei o porquê. Ele era esquisito.","P","Jimmy fez [o albúm de recortes]. Era um aviso, Eu deveria ter prevido que algo aconteceria.","H","Jimmy usava para colar histórias de jornais sobre professores e doutores abusivos. Ele não era um moleque normal.","R","Harvey disse que o Jimmy fez [o albúm de recortes], mas eu não me recordo."],
  ["P","Eu amarrei [o varal e o rolo de macarrão] juntos. Era um experimento."],
  ["H","[O velho aquecedor] estava dando choque. Eu guardei para que a polícia checasse.","R","Harvey jogou [o aquecedor velho] fora. Ele disse que era perigoso."],
  ["A","O menino brincou com [os tacos].","P","Harvey manteve [os tacos]. Eu não sei o porquê.","H","Eu guardei [os tacos], caso eu precisasse.","R","[Os tacos] pertenciam ao meu marido, da época que ele era um professor."],
  ["A","[A besta] estava num armário, no hotel. Eu vi.","P","O hotel costumava ter um mostruário com armas antigas.","H","[A besta] era do mostruário de armamentos que tínhamos. Jimmy era apegado a isso.","R","[A besta] era de uma vitrine que o Harvey costumava ter. Mas eu não gostava de ter aquilo no hotel."],
  ["H","[As chaves enferrujadas] eram da porta da antiga caldeira.","R","[As chaves enferrujadas] eram da sala da caldeira, mas nós tívemos que substituir a porta."],
  ["P","Eu nunca ouvi sobre isso.","H","Eles conseguiram conter, mas eu perdi um monte de coisas.","R","Nós apagamos bem a tempo, antes que se espalhasse."],
  ["P","Harvey era dono [da arma]. Eu não gostava daquilo no hotel.","H","[A arma] era minha. Era do meu pai. Ainda tinha algumas balas com ela.","R","[A arma] pertencia ao Harvey, mas ficava guardada no meu quarto."],
  ["A","Jimmy me mostrou, mas não era dele.","H","Não é uma adaga, é um abridor de cartas. Não é para ser afiado.","R","[A adaga] era um abridor de cartas. Foi presente de alguém."],
  ["R","[O pôster] era do ato de comédia do Jimmy."],
  ["P","Eu não vi [os espelhos quebrados].","H","Não lembro disso.","R","Jimmy quebrou [os espelhos]."],
  ["A","Jimmy costumava carregar com ele por aí.","P","[O fio de cobre] pertencia ao Jimmy. Ele sempre guardava em seu bolso. Ele não me disse para que servia.","H","Jimmy tinha mania de carregar [fio de cobre] com ele por aí. Sei lá porquê.","R","Jimmy costumava carregar fios com ele. Ele gostava de brincar por aí com eletrônicos."],
  ["R","Jimmy escreveu [o bilhete de despedida]."],
  ["H","[A aliança] provavelmente era da Rose.","R","[A aliança] era minha. Alguém me fez uma oferta que eu não pude recusar."],
  ["A","Eu não sei. Eu não vi nenhum bebê.","R","[O chocalho] era para o bebê. Eu guardava na gaveta do criado-mudo."],
  ["R","Jimmy é filho do Hugo. De qualquer forma."],
  ["A","Um menino chamado Jimmy me trancou no porão. Aí ele começou a roubar coisas de mim.","P","[A garota] era filha de um dos hóspedes. Jimmy não era legal com ela.","H","[A menina] estava no hotel com a família dela.","R","[A menina] era uma hóspede do hotel."],
  ["A","[Jimmy] pensou que [roubar meu brinquedo] era divertido. Ele devolveu, mas já estava destruído mesmo.","P","Era apenas o tipo de coisa que [Jimmy] fazia.","H","[Jimmy] provavelmente achou que seria engraçado.","R","A menina estava mentindo. Jimmy não roubava coisas."],
  ["A","Minha mão queimou, estava doendo mesmo, mas eu não podia contar pra ninguém.","P","A mão [da menina] foi queimada gravemente, mas Jimmy pensou que era tudo uma piada.","H","[A garota] estava queimada, bem feio","R","[A menina] se queimou, mas ela continuava fazendo coisas perigosas daquele tipo. Ela era estranha."],
  ["A","Eu estava tentando achar um doutor, mas Jimmy me ameaçou e me fez ficar.","H","[A garota] provavelmente tava com medo do Jimmy.","R","[A razão da Amy estar assustada] poderia ser qualquer coisa. Ela era uma menina estranha."],
  ["A","O menino me disse que era remédio. Tinha um gosto horrível.","P","Eu não estava lá então, mas eu acho que ela tomou álcool."],
  ["A","Eu me senti super leve, eu achei mesmo que podia pular até lá embaixo.","P","Jimmy fez a menina beber muito.","H","[A garota tinha] bebido uma garrafa de whiskey, ela não sabia o que estava fazendo.","R","Eu não conhecia muito [a menina]."],
  ["A","Eu pulei, mas então tudo ficou escuro e eu não consegui mais acordar. Eu não posso acordar mais.","P","[A menina] caiu pela escadaria desde o último andar. Ela estava embriaga demais para saber o que estava fazendo. Foi a razão pela qual a Rose entrou em contato comigo.","H","[A garota] caiu do andar mais alto até o final da escadaria. Eu sabia que o Jimmy tava por trás disso.","R","[A menina] caiu. Harvey culpou o Jimmy por isso. Foi culpa da menina, não do Jimmy."],
  ["P","Eu recebi uma ligação da Rose. Ela gostaria que eu descobrisse o que estava chateando o Jimmy. Mas o Harvey estava preocupado com as coisas que o Jimmy estava imaginando.","H","Era pro Doutor Bose supostamente ajudar o Jimmy, mas o Jimmy estava além de qualquer ajuda.","R","Doutor Bose veio para ajudar o Jimmy."],
  ["P","Jimmy estava matando coisas. Eu percebi que ele precisava trabalhar sua empatia. Então eu pedi para ele pensar em algo legal que ele poderia fazer para mim. Ele teve uma ideia de imediato.","H","Jimmy falou que ele achou [o coelho morto] por aí. O que ele estava fazendo com aquilo, é uma outra história.","R","Harvey disse que o Jimmy provavelmente tinha matado [o coelho] ele mesmo, mas eu não acreditei nele."],
  ["P","Jimmy estava me fazendo um sanduíche. Ele trouxe até meu quarto, como eu pedi. Eu não suspeitei que algo estava errado de início.","H","O médito tava tentando educar o Jimmy, fazer ele ajudar. Grande erro.","R","Doutor Bose ficou tentando que o Jimmy fizesse coisas que ele não queria."],
  ["P","Jimmy tinha colocado cacos de vidro no meu sanduíche. Eu quase engasguei. Eu percebi que subestimei a doença do Jimmy. Eu tive que dar inicío ao tratamento dele, com urgência.","H","[Doutor Bose] aprendeu sobre o Jimmy do jeito difícil. As pegadinhas do Jimmy sempre iam longe demais.","R","[Doutor Bose] se cortou, mas então tentou culpar o Jimmy. Ele fez aquilo com ele mesmo, não foi o Jimmy."],
  ["P","Jimmy se negou a deixar eu administrar o medicamento. Então ele contou para a Rose que eu tentei forçá-lo a tomar, que eu havia usado violência. Foi ridículo!","H","Não sei, eu não tava lá.","R","[Doutor Bose] estava tentando medicar o Jimmy, sem minha permissão."],
  ["P","Eu estava preocupado de que Rose iria acreditar no Jimmy. Mentiu na cara de pau. Mas eu convenci a Rose de que Jimmy estava inventando tudo.","H","[Doutor Bose] tava preocupado com o que mais o Jimmy ia fazer contra ele. E ele tinha razão de estar.","R","Porque o [Doutor Bose] estava preocupado com sua reputação. Mas eu decidi dar a ele uma segunda chance."],
  ["P","Eu pensei que quando o [Jimmy] percebesse que foi pego mentindo, ele começaria a engajar comigo. Ao invés disso ele inventou outra desculpa. Uma pior. Muito pior.","R","[Doutor Bose] estava conversando com o Jimmy, tentando controlá-lo. Levá-lo a fazer coisas ruins. Eu nunca deveria ter confiado nele."],
  ["P","Rose me denunciou. Eu sabia que eles me expulsariam. Ficaria sem carreira, sem futuro. Eu decidi tomar o controle, de uma vez por todas.","H","Eles iam prender o [Doutor Bose]. Jimmy acabou com ele. Mas eu não acreditava em nada disso.","R","Eles vieram prender o [Doutor Bose]. Ele merecia tudo que teve."],
  ["P","Eu tive o bastante. Não tinha mais volta. Minha vida tinha acabado de qualquer forma.","H","[Doutor Bose foi] levado a isso. Todo mundo achou que ele tinha 'tocado' o Jimmy. Jimmy era muito inteligente. O doutor não tinha chance.","R","[Doutor Bose] sabia que era culpado. Ele fez a coisa certa."],
  ["P","Harvey sabia que Jimmy estava mentindo sobre mim. Harvey entendeu.","H","Jimmy fez acusações sobre o doutor. A Rose acreditou nele, mas eu tinha escutado aquela história em algum outro lugar.","R","Harvey não acreditou no que Jimmy estava falando [sobre o doutor], mas eu sabia que ele não estava mentindo."],
  ["P","Jimmy nunca admitiu suas mentiras.","H","Jimmy apenas ria. Então ele começou a montar pequenas armadilhas pra mim. Algumas delas não tão pequenas.","R","Como o Jimmy poderia admitir algo que não era verdade? Harvey estava errado em implicar com o Jimmy daquele jeito."],
  ["H","[Jimmy] sabia que era meu aquecedor, ele ligou a carcaça direto na rede elétrica. Eu sabia que ele precisava aprender uma lição. Ele destrui minha propriedade então eu decidi destruir a dele.","R","Harvey culpou o Jimmy, mas aquele aquecedor era defeituoso. Harvey deveria ter jogado fora."],
  ["P","Eu não sei [o que Harvey estava fazendo com o taco], mas violência só piora as coisas.","H","Eu destruí a teleivsão do [Jimmy] e os vídeo-games. Eu estava enfurecido. Mas não funcionou. Só fez ele ficar pior. Ele logo se vingaria.","R","[Harvey] destruiu as coisas do Jimmy. Ele não conseguia controlar sua raiva."],
  ["H","Jimmy tinha armado [a besta] para atirar quando eu abrisse a porta. Eu tive que ir pro pronto-socorro. Quando eu voltei, não consegui encontrar ele. Rose me disse que ele estava se escondendo no porão. Isso me deu uma ideia.","R","Harvey disse que Jimmy tinha atirado uma flecha nele, mas eu sabia que Jimmy não usaria uma arma assim."],
  ["H","Eu queria dar ao Jimmy uma dose do seu próprio veneno. Eu pensei que ele não seria capaz de causar qualquer dano [no porão]. Eu tava errado.","R","Eu não sei o que [Harvey] estava fazendo [no porão]."],
  ["P","Eu não me recordo do [incêncio no hotel].","H","A gente conseguiu conter [o incêndio no hotel] antes que ficasse fora de controle. Mas todas nossas fotos antigas e cartas estavam lá, tudo acabou virando chamas. Jimmy tava fora de controle, eu cansei dele. Queria que ele fosse embora.","R","Harvey culpou o Jimmy [pelo incêndio no hotel], mas havia um fio desencapado que começou aquele incêndio. Foi um acidente."],
  ["P","Eu não sei [de onde veio aquele arma]. Mas Harvey não era capaz de controlar sua raiva.","H","Eu não sabia o que ia fazer [com a arma]. O problema era, que eu não me dei conta que Jimmy iria se armar também.","R","Eu não sei [de onde surgiu aquela arma]. Harvey não deveria ter uma arma no hotel."],
  ["H","Eu tava procurando o Jimmy."],
  ["H","Jimmy se esgueirou por trás de mim, Eu não vi ele. Jimmy sempre ganhava no final.","R","Harvey ficou louco. Jimmy só estava se defendendo."],
  ["H","Rose acreditou no Jimmy. Ela defendeu ele, até o fim.","R","Eu tive que explicar para a polícia que a adaga era só um abridor de cartas e que Harvey tinha uma arma carregada. Jimmy agiu em legítima defesa. Eles entenderam."],
  ["H","[A polícia] deixou Jimmy ir. Eles disseram que foi legítima defesa, que eu tentei atirar no Jimmy. Mas era tudo mentira.","R","Jimmy estava voltando pra casa. A polícia compreendeu [que foi auto-defesa]. Mas isso o mudou, Jimmy começou a ajudar a tocar o hotel. E ele achou um meio de trazer mais hóspedes."],
  ["H","Eu não sabia quem [Hugo Punch] era.","R","Eu estava gostando, estavámos fazendo dinheiro de novo. Então Jimmy começou a se comportar estranho. Eu ouvi ele gritando, encarando a si mesmo. Ele parecia zangado."],
  ["R","Eu não entendi de início, eu estava confusa. Mas então eu percebi que Jimmy não era quem estava fazendo aquelas coisas. Como os espelhos, ele começou a estilhaçar. Jimmy não estava no controle mais."],
  ["H","Eu não sei, mas eu sei que Jimmy sempre estraga tudo eventualmente.","R","Não era o Jimmy no palco mais, era Hugo Punch. Ele começou a ofender seu público toda noite Então uma noite depois do show uma hóspede disse ao Jimmy o que ela pensava sobre ele. Ele perdeu a paciência e fez algo estúpido."],
  ["R","Jornalistas [estavam batendo na porta], eles queriam o Jimmy. Mas foi o Hugo Punch quem amarrou a mulher. Jimmy não conseguia controlá-lo mais. Ele estava deprimido. Ele só queria deixar tudo para trás e ir embora."],
  ["R","Era o Jimmy [na banho]. Ele tentou se matar. Foi por isso que eu tive que contar à ele a verdade."],
  ["H","Eu não sei [quem a Rose estava atacando]. Tinham coisas que a Rose nunca tinha me contado.","R","Eu enterrei o Hugo [no porão] sob concreto, em um quarto secreto. Eu deixei ele abusar do Jimmy por tempo demais. Era minha culpa o Jimmy ter mudado daquele jeito. Eu pensei que a culpa iria embora se eu contadsse ao Jimmy. Eu estava errada, só piorou. Eu não conseguia aceitar o que eu fiz. Eu não era capaz de viver comigo mesma."],
  ["R","Se eu não tivesse me [matado] o Jimmy teria feito, ou pior, Hugo teria. Hugo ainda está no comando, mesmo agora. Ele está controlando o Jimmy. Peça ao Jimmy para mostrar aonde o Hugo mora."],
  ["H","Eu nunca conheci [O Grande Hugo].","R","Hugo foi um artista e mágico. Ele comprou o hotel para promover seu show de palco. Ele se tornou famoso. Eu trabalhei como sua assistente, então as coisas evoluíram."],
  ["R","Eu nunca soube o que ele queria. Só havia uma coisa que eu poderia dar a ele."],
  ["R","Hugo era um homem violento, vil, doente."],
  ["A","Sim! [Jimmy] pegou quando eu não estava olhando e roubou meu dinheiro. Eu briguei com ele mas ele não me deu ouvidos."],
  ["A","[Jimmy] encharcou meu brinquedo com aquela coisa na garrafa. Eu odiava ele!"],
  ["A","[Jimmy] pegou a espada da parede, parecia muito afiada. Ele me fez prometer que eu não contaria pra ninguém e disse que podia fazer minha mão parar de doer."],
  ["A","[Jimmy] me disse para continuar bebendo [o remédio]. Era horrível. Então eu comecei a me sentir estranha."],
  ["P","[Os desenhos violentos] sugeriam uma personalidade turbulenta, mas eu não estva particularmente preocupado até eu perceber quão longe a imaginação do [Jimmy] foi."],
  ["P","Jimmy disse que faria algo para mim, então eu o segui para ver o que ele iria fazer."],
  ["P","[Jimmy colocando cacos de vidro no sanduíche] foi meu primeiro contato como senso de humor do Jimmy."],
  ["P","[Diazepam] não era a medicação ideal, mas era tudo que eu tinha. Jimmy precisava de tratamento imediatamente. Ele era perigoso."],
  ["P","Jimmy disse que eu havia usado o remo para bater nele. Eu nunca iria usar violência contra um paciente, foi ridículo! Mas a Rose acreditou nele."],
  ["P","Jimmy me acusou do pior crime possível. Ele pegou de uma história de jornal que ele leu. Ele estava inventando tudo."],
  ["P","Eu experimentei com o varal, mas era muito fino. Eu encontrei uma corda ao invés. Eu ainda tinha minhas chaves para o hotel então eu entrei escondido uma noite enquando estava na condicional."],
  ["H","Assim que encontrei o albúm de recortes eu soube que Jimmy tinha pego [A história] de lá. Era o mesmo caso, detalhe por detalhe."],
  ["H","Jimmy tava sempre brincando com eletricidade. Engraçado que quem tomava choque nunca era ele."],
  ["H","Eu guardei aqueles tacos pra me defender, mas eu estava enfurecido. Eu peguei um deles e fui até o quarto do Jimmy."],
  ["H","Jimmy era apegado em armas tipo [a besta]. Eu não tinha visto o Jimmy a noite toda depois que eu destruí suas coisas. Eu devia ter adivinhado que ele tava trabalhando no seu próximo truquezinho."],
  ["H","Bem, se o Jimmy queria se esconder [no porão] eu pensei que ele gostava."],
  ["H","Ninguém se deu conta do quão longe Jimmy iria para ter atenção."],
  ["H","Eu perdi a noção. Tava com sangue nos olhos, eu odiava ele. Eu perdi o controle."],
  ["H","[O abridor de cartas] não era nem uma adaga! Mas eu nunca aprendia minha lição, Jimmy sempre estava dois passos à frente."],
  ["R","Jimmy começou a fazer um ato de comédio no palco: Hugo Punch. Ele era bom. Pessoas começaram a vir só para assistí-lo."],
  ["R","Quebrar os espelhos foi só o começo. Ele não lembrava de ter feito isso. Então outras coisas estranhas começaram a acontecer."],
  ["R","Jimmy trancou [a mulher que fez uma reclamação] no quarto e amarrou ela. Eu encontrei ela e a soltei. Ela não prestou queixa, mas contou aos jornais."],
  ["R","Jimmy vinha lutando contra o Hugo Punch toda sua vida. Jimmy não queria viver mais."],
  ["R","[Hugo e eu] éramos casados. Éramos felizes no começo, antes das coisas começarem a mudar."],
  ["R","Eu pensei que ter uma criança resolveria tudo. Eu estava errada."],
  ["R","Eu admiti tudo ao Jimmy. Hugo batia no Jimmy desde que ele nasceu, até seus 2 anos. Eu deveria ter impedido antes."],
  ["R","Jimmy foi atrás do tumulo do Hugo. Eu estava sozinha. Eu sabia o que tinha que fazer."],
],

finwords:[

  "Em cada um de nós há outro<br>que não conhecemos.",7,
  "",0.5,
  "Ele fala conosco nos sonhos,",6,
  "e nos conta quão diferente ele nos vê<br>da forma como vemos nós mesmos.<br><span class='h8'>Carl Jung</span>",8,
  "V",5,
  "Você pode vê-los,",4,
  "",0.5,
  "At Dead Of Night",5,
  "",16,
  "<span class='hf'>Maya</span><br>Chloe Booyens",5,
  "<span class='hf'>Jimmy Hall</span><br>Huld Martha",5,
  "<span class='hf'>Rose Hall</span><br>Joanna Bond",5,
  "<span class='hf'>Harvey</span><br>Karl Haynes",5,
  "<span class='hf'>Dr Bose</span><br>Rohit Gokani",5,
  "<span class='hf'>Amy Bell</span><br>Daisy Follin",5,
  "<span class='hf'>Com os atores coadjuvantes</span><br>Rachel Alfieri<br>Paige Ryan<br>Sally Alfieri<br>Daniel Alfieri<br>Luke Chase",8,
  "<span class='hf'>Com os atores coadjuvantes</span><br>Sam Follin<br>Jamie Follin<br>Tom Follin<br>Clare Follin",7,
  "<span class='hf'>Agradecimento especial a</span><br>Mark Wilson<br>Fay Wilkins",7,
  "",1,
  "Obrigado por jogar<br>At Dead Of Night",8,
  "",

],

words:[

  "LIGAR O DISPOSITIVO",
  "DESLIGAR O DISPOSITIVO",
  "CHAMAR",
  "USAR O ESPELHO DA PREVISÃO",
  "FAZER PERGUNTA",
  "FECHAR",
  "Perguntar<br>quem<br>está aí",
  "Perguntar<br>o seu<br>nome",
  "É isso<br>",
  "CORRE EM FRENTE",
  "APERTAR<br>PISO<br>INFERIOR",
  "APERTAR<br>ANDAR<br>TERREO",
  "APERTAR<br>1º<br>ANDAR",
  "APERTAR<br>2º<br>ANDAR",
  "APERTAR<br>3º<br>ANDAR",
  "VOLTAR",
  "ABRIR<br>MENU",
  "Chamar por Jimmy",
  "TENTAR ABRIR<br>PORTA<br>",
  "TENTAR ABRIR<br>QUARTO<br>",
  "VOLTAR<br>PARA O QUARTO",
  "MANDAR<br>AMIGO<br>FUGIR",
  "VOCÊ<br>COMBINOU ESTES",
  "TENTAR<br>DEPÓSITO<br>CINCO",
  "CHAMAR<br>ELEVADOR",
  "PERGUNTAR SOBRE ISSO",
  "ESCONDER<br>NO<br>ARMÁRIO",
  "ESCONDER<br>NO<br>BANHEIRO",
  "OLHAR<br>PELO<br>OLHO MÁGICO",
  "ENTRAR<br>NO<br>QUARTO",
  "PROCURAR<br>AQUI",
  "SAIR<br>DAQUI",
  "TENTAR<br>ESTA<br>PORTA",
  "FECHAR",
  "ABRIR<br>NOTAS",
  "ADICIONAR PARA<br>COMBINAR",
  "VOLTAR<br>PARA A<br>PORTA",
  "COMBINAR VISÕES<br><span style='font-family:arial'>E</span> OBJETOS",
  "PERGUNTAR SE ESTES SE RELACIONAM",
  "PERGUNTAR",
  "PRÓXIMA PAGINA",
  "PAGINA ANTERIOR",
  "TENTAR ABRIR A PORTA DA ESCADARIA",
  "MUITO ESCURO<br>EM FRENTE",
  "ENTRAR NO<br>QUARTO",
  "SAIR DO<br>TUTORIAL",
  "Procure no depósito do primeiro andar perto das escadas pelo dispositivo.",
  "Você precisa<br>achar o espelho<br>da previsão",
  "Você precisa<br>achar a<br>bússola",
  "Você precisa<br>achar a bússola<br>e o espelho da previsão",
  "Jogo<br>Salvo",
  "OLHAR PELA<br>JANELA",
  "Espere até estar seguro primeiro.",
  "SAIR",
  "Essa é a chave errada",
  "Porta destrancada",
  "Vá até uma porta trancada<br>para testar a chave",
  "Porta trancada",
  "Tenta a porta primeiro",
  "Usa a chave do quarto<br>para trancar o quarto",
  "Destranca a porta primeiro",
  "SUBIR",
  "DESCER",
  "Está muito escuro aqui para usar o dispositivo",
  "Espere um pouco antes de tentar entrar em contato novamente.",
  "O Jimmy está entrando no quarto!",
  "Você pode ouvir Jimmy em algum lugar",
  "O Jimmy ri silenciosamente",
  "Comece o jogo primeiro",
  "Não pode gravar agora",
  "Jogo Atual Salvo",
  "Ainda não pode usar o espelho",
  "Não tente!<br>O Jimmy está no quarto!",
  "OLHAR<br>PELA<br>FECHADURA",
  "É melhor deixar os depósitos destrancados.",
  "PEGAR<br>DISPOSITIVO",
  "Está muito escuro aqui para usar o espelho",
  "Depósito",
  "Desconhecido",
  "Tem muita luz aqui para usar o espelho",
  "VOLTAR PARA<br>O MENU",
  "Salvar<br>o Jogo?",
  "SALVAR",
  "Você pode ouvir Jimmy andando por perto",
  "Você pode ouvir Jimmy andando rapidamente",
  "A porta do quarto foi fechada",
  "PULAR<br>DESPERTAR",
  "Procure nos depósitos pelo dispositivo.",
  "PULAR",
  "FECHAR MENSAGEM",

],

ghostex:[

  "A",
  "Em Contato Com<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;AMY&#160;&#160;</span>&#10023;<br><br>Menina com 10 Anos",
  "P",
  "Em Contato Com<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;Dr BOSE&#160;&#160;</span>&#10023;<br><br>Psiquiatra Clínico",
  "H",
  "Em Contato Com<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;HARVEY&#160;&#160;</span>&#10023;<br><br>Dono Do Hotel",
  "R",
  "Em Contato Com<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;ROSE&#160;&#160;</span>&#10023;<br><br>Dono Do Hotel",

],

headtex:[

  "<span class='h3'>Ache O Receptor.</span>",
  "<span class='h3'>Ligue O Receptor<br>Para Comunicar Com Espíritos.</span>",
  "<span class='h3'>Aumente O Volume Do Receptor Para Ouvir A Resposta Dos Espíritos.</span>",
  "<span class='h3'>Tente Entrar Em Contato Com Um Espírito</span><br><span class='h2'>(Use O Ícone Acima Para Falar)</span>",
  "<span class='h3'>Um Espírito Está Entrando Em Contato.<br>Tente Confirmar A Identidade Dele.</span>",
  "<span class='h3'>Em Contato Com ",
  "<span class='h3'>Espírito muito distante. Tente se aproximar.</span>",
  "<span class='h2'>Quando Você Conhecer Espíritos, Pode Fazer Perguntas. Combine As Respostas Deles Para Fazer Conexões. Quando Você Estiver Sozinho, Pode Revisar As Respostas dos Espíritos Aqui.</span>",

],

gametex:[

  "O Jogo Padrão<br><br><span class='h2'>Encontra Espíritos, faça perguntas a eles e faça conexões para fazê-los aparecer, enquanto Jimmy tenta parar você de descobrir os seus segredos.</span>",
  "Busca e Resgate<br><br><span class='h2'>Resgata os teus amigos enquanto Jimmy tenta parar você. Se ele acertar você uma vez, você perde.</span>",
  "Busca e Resgate<br><br><span class='h2'>Voltar ao final do seu último jogo.</span>",
  "<span class='h9'>Selecione Um Modo</span><br><br><span class='h2'>Escolha o Modo Padrão ou Modo Extremo. Ao jogar no Modo Extremo, caso Jimmy te ataque, ele roubará quase todos os seus itens, todas as vezes.<br><br>Seu jogo atual será perdido quando você começar um novo jogo e suas conquistas serão reiniciadas.</span>",
  "<span class='h9'>Tem a certeza?</span><br><br><span class='h2'>Isso encerrará seu jogo atual e retornará ao seu último jogo salvo.</span>",
  "<span class='h9'>Um Golpe e Você Está Morto!</span><br><br><span class='h2'>Este jogo não salva, então você tem apenas uma chance de resgatar todos!</span>",

],

getex:[

  "<br>Você Achou<br><br>Um Espelho De<br><br>Previsão<br><br><span style='font-size:50%'>Revela Dicas e Pistas<br>Quando Usado Em<br>Lugares Escuros</span>",
  "<br>Você Achou<br><br>Uma Bússola<br><br><span style='font-size:50%'>Aponta Na Direção De<br>Espíritos Próximos</span>",
  "<span style='font-size:40%>'>Você Achou A<br>Chave:<br>",
  "Você Achou A<br>chave-raxa<br>Para O Quarto",
  "Você Achou A<br>chave-raxa<br>Para O Quarto",

],

roomtex:"Quarto",

foundtex:"Você achou",

alreadytex:[

  "Você Já Tem Um Espelho De Previsão",
  "Você Já Tem Uma Bússola"

],

adtext:[

  "Som de uma<br>menina chorando",
  "Sons de um fliperama",
  "Som de uma menina<br>chorando baixinho",
  "Uma menina cantando<br>suavemente",
  "Alguem batendo<br>suavemente na porta",
  "Som de louça sendo movimentada",
  "Som de uma<br>torneira aberta",
  "Som de<br>telefone sendo discado",
  "Batidas fortes<br>em uma porta",
  "Som de alguem<br>batendo na porta",
  "Som de faíscas e<br>chiados elétricos",
  "Som de coisas<br>sendo esmagadas",
  "Som intermitente de<br>batidas ou estalos",
  "Alguem batendo<br>numa porta de metal",
  "Um Alarme barulhento",
  "Harvey gritando com Jimmy",
  "Murmurinho<br>de uma multidão",
  "Música tocando<br>de um rádio",
  "Uma multidão vaiando e gritando alto",
  "Uma campainha tocando insistentemente",
  "Som de água correndo em uma banheira",
  "Som ocasional<br>de chicotadas",
  "Música sendo tocada",

],

itdetext:[

  "Maletas",
  "Troféus",
  "Bolsa de Criança",
  "Aguarras e Isqueiro",
  "Espada Ornamental",
  "Garrafas de Whiskey",
  "Desenhos Violentos",
  "Chapéu de Chef",
  "Pano Manchado de Sangue",
  "Diazepam",
  "Remo",
  "Albúm de Recortes",
  "Varal",
  "Aquecedor Perigoso",
  "Tacos",
  "Besta",
  "Chaves Enferrujadas",
  "Fotos de um Incêndio",
  "Pistola",
  "Adaga Ornamental",
  "Póster do Hugo Punch",
  "Espelhos Quebrados",
  "Bobina de Fio",
  "Bilhete de despedida",
  "Aliança de Casamento",
  "Chocalho de Bebê",
  "Certidão de Nascimento",
  "Menina no Porão",
  "Jimmy Roubando de Amy",
  "Amy Segurando Um Brinquedo Em Chamas",
  "Amy Assustada Fora Do Quarto",
  "Amy Bebendo Algo Horrível",
  "Amy No Topo Das Escadas",
  "Amy No Fundo Das Escadas",
  "Homem de Terno Batendo na Porta",
  "Dr Bose Achando Um Animal Morto",
  "Dr Bose Fora Da Cozinha",
  "Dr Bose Cuspindo Sangue",
  "Dr Bose Com Uma Agulha de Injeção",
  "Dr Bose Explicando O Que Aconteceu",
  "Dr Bose Sentado Em Uma Cama Em Um Quarto",
  "Dr Bose Na Sala De Jogos",
  "Dr Bose Se Matando",
  "O Homem Falando Que O Jimmy Mentiu",
  "Harvey Gritando Pela Porta",
  "Harvey Sendo Eletrocutado",
  "Harvey Com Um Taco",
  "Harvey Levando Um Tiro Na Perna",
  "Harvey Trancando Jimmy No Porão",
  "Um Incêndio No Porão",
  "Harvey Com Uma Pistola",
  "Harvey Indo Para O Salão De Baile",
  "Harvey Sendo Esfaqueado",
  "Senhora Explicando A Adaga",
  "Rose Na Porta De Entrada",
  "Rose nos Bastidores Anunciando Hugo Punch",
  "Rose Encontrando Muitos Manequins",
  "Rose Pedindo Desculpas a um Hóspede",
  "Rose Se Escondendo E Pessoas Batendo Na Porta",
  "Rose Encontrando Jimmy No Banheiro",
  "Rose Atacando Alguem Com Um Taco",
  "Rose Em Chamas",
  "O Grande Hugo No Palco",
  "Homem Gritando E Criança Chorando",
  "Gritando E Elevador Caindo",
  "Jimmy Não Ouvia",
  "Jimmy Molhou o Brinquedo de Amy",
  "Jimmy Poderia Parar a Dor na Mão de Amy",
  "Amy Bebeu Algo Horrível",
  "Dr Bose Viu Os Desenhos de Jimmy",
  "Jimmy Teve Uma Ideia",
  "Dr Bose Encontrou o Humor de Jimmy",
  "Dr Bose Decidiu Medicar Jimmy",
  "Jimmy Acusou Dr Bose De Violência",
  "Jimmy Acusou Dr Bose De Abuso",
  "Dr Bose Sabia O Que Ele Devia Fazer",
  "Harvey Descobriu O Albúm de Recortes de Jimmy",
  "Jimmy Brincou Com Eletricidade",
  "Harvey Levou Um Taco Para O Quarto De Jimmy",
  "Harvey Suspeitou De Outra Armadilha",
  "Harvey Usou a Chave da Sala da Caldeira",
  "Harvey Percebeu que Jimmy Era Louco",
  "Harvey Perdeu O Controle",
  "Jimmy Estava Um Passo À Frente",
  "Jimmy Começou O Seu Ato De Comédia",
  "Coisas Estranhas Começaram A Acontecer",
  "Os Jornais Descobriram",
  "Jimmy Já Tinha Chegado Ao Limite",
  "As Coisas Mudaram Com Hugo",
  "Um Bebê Não Resolve Nada",
  "A Verdade Foi Revelada",
  "Rose Foi Dominada Pela Culpa",
  "Chave para o&#160;'Depósito'",
  "",
  "",
  "Espelho da Previsão",
  "Bússola",
  "Chave para a 'Escadaria do Primeiro Andar'",
  "",
  "",
  "Espelho da Previsão",
  "Bússola",
  "Chave para o&#160;'Depósito'",
  "",
  "",
  "Espelho da Previsão",
  "Bússola",
  "Chave para a 'Escadaria do Segundo Andar'",
  "",
  "",
  "Espelho da Previsão",
  "Bússola",
  "Chave para o&#160;'Depósito'",
  "",
  "",
  "Espelho da Previsão",
  "Bússola",
  "Chave para a 'Escadaria do Terceiro Andar'",
  "",
  "",
  "Espelho da Previsão",
  "Bússola",
  "Chave para o&#160;'Depósito'",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Chave da Saída do Hotel",
  "Chave do Depósito no Porão",

],

keyfinds:[

    "Depósito",
    "ESCADAS<br>PRIMEIRO ANDAR",
    "ESCADAS<br>SEGUNDO ANDAR",
    "ESCADAS<br>TERCEIRO ANDAR",

  ],

gnames:[
  "Amy",
  "Dr Bose",
  "Harvey",
  "Rose",
  "Hugo"
],

extras:[
  "BEM VINDO AO <br>SEA VIEW HOTEL<br><span style='font-size:50%'>FAÇA A SUA RESERVA AQUI</span>",
  "Maya:",
  "Jogo Salvo",
  "Comando Conectado",
  "Comando Desconectado",
],

};
